/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppClassesIndexRouteImport } from './routes/_app/classes/index'
import { Route as AppClassesEnrollRouteImport } from './routes/_app/classes/enroll'
import { Route as AppClassesNewRouteImport } from './routes/_app/classes/new'
import { Route as AppComponentsIndexRouteImport } from './routes/_app/components/index'
import { Route as AppComponentsNewRouteImport } from './routes/_app/components/new'
import { Route as AppMeetingsIndexRouteImport } from './routes/_app/meetings/index'
import { Route as AppMeetingsNewRouteImport } from './routes/_app/meetings/new'
import { Route as AppRolesIndexRouteImport } from './routes/_app/roles/index'
import { Route as AppRolesNewRouteImport } from './routes/_app/roles/new'
import { Route as AppStaffIndexRouteImport } from './routes/_app/staff/index'
import { Route as AppStaffNewRouteImport } from './routes/_app/staff/new'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students/index'
import { Route as AppStudentsImportRouteImport } from './routes/_app/students/import'
import { Route as AppStudentsNewRouteImport } from './routes/_app/students/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiClassesIndexRouteImport } from './routes/api/classes/index'
import { Route as ApiComponentsIndexRouteImport } from './routes/api/components/index'
import { Route as ApiEnrollmentsIndexRouteImport } from './routes/api/enrollments/index'
import { Route as ApiMeetingsIndexRouteImport } from './routes/api/meetings/index'
import { Route as ApiMinuteTemplatesIndexRouteImport } from './routes/api/minute-templates/index'
import { Route as ApiRolesIndexRouteImport } from './routes/api/roles/index'
import { Route as ApiStaffIndexRouteImport } from './routes/api/staff/index'
import { Route as ApiStudentsIndexRouteImport } from './routes/api/students/index'
import { Route as ApiStudentsImportRouteImport } from './routes/api/students/import'
import { Route as AppClassesIdOffersRouteImport } from './routes/_app/classes/$id/offers'
import { Route as AppClassesIdStudentsRouteImport } from './routes/_app/classes/$id/students'
import { Route as AppMeetingsMeetingIdIndexRouteImport } from './routes/_app/meetings/$meetingId/index'
import { Route as AppMeetingsMeetingIdCouncilRouteImport } from './routes/_app/meetings/$meetingId/council'
import { Route as AppMeetingsMeetingIdParticipantsRouteImport } from './routes/_app/meetings/$meetingId/participants'
import { Route as AppMeetingsMeetingIdStudentsRouteImport } from './routes/_app/meetings/$meetingId/students'
import { Route as ApiClassesIdHistoryRouteImport } from './routes/api/classes/$id/history'
import { Route as ApiClassesIdOffersRouteImport } from './routes/api/classes/$id/offers'
import { Route as ApiClassesIdStudentsRouteImport } from './routes/api/classes/$id/students'
import { Route as ApiMeetingsMeetingIdIndexRouteImport } from './routes/api/meetings/$meetingId/index'
import { Route as ApiMeetingsMeetingIdFinalizeRouteImport } from './routes/api/meetings/$meetingId/finalize'
import { Route as ApiMeetingsMeetingIdParticipantsRouteImport } from './routes/api/meetings/$meetingId/participants'
import { Route as ApiMeetingsMeetingIdReopenRouteImport } from './routes/api/meetings/$meetingId/reopen'
import { Route as ApiMeetingsMeetingIdStartRouteImport } from './routes/api/meetings/$meetingId/start'
import { Route as ApiStaffIdIndexRouteImport } from './routes/api/staff/$id/index'
import { Route as ApiStudentsIdHistoryRouteImport } from './routes/api/students/$id/history'
import { Route as ApiStudentsIdRecordsRouteImport } from './routes/api/students/$id/records'
import { Route as ApiStudentsImportResolveRouteImport } from './routes/api/students/import.resolve'
import { Route as ApiMeetingsMeetingIdGeneralReportsIndexRouteImport } from './routes/api/meetings/$meetingId/general-reports/index'
import { Route as ApiMeetingsMeetingIdGeneralReportsReportIdRouteImport } from './routes/api/meetings/$meetingId/general-reports/$reportId'
import { Route as ApiMeetingsMeetingIdMinutesIndexRouteImport } from './routes/api/meetings/$meetingId/minutes/index'
import { Route as ApiMeetingsMeetingIdMinutesApproveRouteImport } from './routes/api/meetings/$meetingId/minutes/approve'
import { Route as ApiMeetingsMeetingIdRecordsRecordIdRouteImport } from './routes/api/meetings/$meetingId/records/$recordId'
import { Route as ApiMeetingsMeetingIdClassesClassIdStudentsRouteImport } from './routes/api/meetings/$meetingId/classes/$classId/students'
import { Route as ApiMeetingsMeetingIdMinutesVersionsIndexRouteImport } from './routes/api/meetings/$meetingId/minutes/versions/index'
import { Route as ApiMeetingsMeetingIdStudentsStudentIdStatusRouteImport } from './routes/api/meetings/$meetingId/students/$studentId/status'
import { Route as ApiMeetingsMeetingIdMinutesVersionsVersionPdfRouteImport } from './routes/api/meetings/$meetingId/minutes/versions/$version/pdf'
import { Route as ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRouteImport } from './routes/api/meetings/$meetingId/students/$studentId/records/index'
import { Route as ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRouteImport } from './routes/api/meetings/$meetingId/students/$studentId/records/$recordId/include'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClassesIndexRoute = AppClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClassesEnrollRoute = AppClassesEnrollRouteImport.update({
  id: '/classes/enroll',
  path: '/classes/enroll',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClassesNewRoute = AppClassesNewRouteImport.update({
  id: '/classes/new',
  path: '/classes/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComponentsIndexRoute = AppComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComponentsNewRoute = AppComponentsNewRouteImport.update({
  id: '/components/new',
  path: '/components/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsIndexRoute = AppMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsNewRoute = AppMeetingsNewRouteImport.update({
  id: '/meetings/new',
  path: '/meetings/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesNewRoute = AppRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStaffNewRoute = AppStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsImportRoute = AppStudentsImportRouteImport.update({
  id: '/students/import',
  path: '/students/import',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesIndexRoute = ApiClassesIndexRouteImport.update({
  id: '/api/classes/',
  path: '/api/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComponentsIndexRoute = ApiComponentsIndexRouteImport.update({
  id: '/api/components/',
  path: '/api/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrollmentsIndexRoute = ApiEnrollmentsIndexRouteImport.update({
  id: '/api/enrollments/',
  path: '/api/enrollments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsIndexRoute = ApiMeetingsIndexRouteImport.update({
  id: '/api/meetings/',
  path: '/api/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMinuteTemplatesIndexRoute = ApiMinuteTemplatesIndexRouteImport.update({
  id: '/api/minute-templates/',
  path: '/api/minute-templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRolesIndexRoute = ApiRolesIndexRouteImport.update({
  id: '/api/roles/',
  path: '/api/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffIndexRoute = ApiStaffIndexRouteImport.update({
  id: '/api/staff/',
  path: '/api/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIndexRoute = ApiStudentsIndexRouteImport.update({
  id: '/api/students/',
  path: '/api/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsImportRoute = ApiStudentsImportRouteImport.update({
  id: '/api/students/import',
  path: '/api/students/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClassesIdOffersRoute = AppClassesIdOffersRouteImport.update({
  id: '/classes/$id/offers',
  path: '/classes/$id/offers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClassesIdStudentsRoute = AppClassesIdStudentsRouteImport.update({
  id: '/classes/$id/students',
  path: '/classes/$id/students',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsMeetingIdIndexRoute =
  AppMeetingsMeetingIdIndexRouteImport.update({
    id: '/meetings/$meetingId/',
    path: '/meetings/$meetingId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMeetingsMeetingIdCouncilRoute =
  AppMeetingsMeetingIdCouncilRouteImport.update({
    id: '/meetings/$meetingId/council',
    path: '/meetings/$meetingId/council',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMeetingsMeetingIdParticipantsRoute =
  AppMeetingsMeetingIdParticipantsRouteImport.update({
    id: '/meetings/$meetingId/participants',
    path: '/meetings/$meetingId/participants',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMeetingsMeetingIdStudentsRoute =
  AppMeetingsMeetingIdStudentsRouteImport.update({
    id: '/meetings/$meetingId/students',
    path: '/meetings/$meetingId/students',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiClassesIdHistoryRoute = ApiClassesIdHistoryRouteImport.update({
  id: '/api/classes/$id/history',
  path: '/api/classes/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesIdOffersRoute = ApiClassesIdOffersRouteImport.update({
  id: '/api/classes/$id/offers',
  path: '/api/classes/$id/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesIdStudentsRoute = ApiClassesIdStudentsRouteImport.update({
  id: '/api/classes/$id/students',
  path: '/api/classes/$id/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsMeetingIdIndexRoute =
  ApiMeetingsMeetingIdIndexRouteImport.update({
    id: '/api/meetings/$meetingId/',
    path: '/api/meetings/$meetingId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdFinalizeRoute =
  ApiMeetingsMeetingIdFinalizeRouteImport.update({
    id: '/api/meetings/$meetingId/finalize',
    path: '/api/meetings/$meetingId/finalize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdParticipantsRoute =
  ApiMeetingsMeetingIdParticipantsRouteImport.update({
    id: '/api/meetings/$meetingId/participants',
    path: '/api/meetings/$meetingId/participants',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdReopenRoute =
  ApiMeetingsMeetingIdReopenRouteImport.update({
    id: '/api/meetings/$meetingId/reopen',
    path: '/api/meetings/$meetingId/reopen',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdStartRoute =
  ApiMeetingsMeetingIdStartRouteImport.update({
    id: '/api/meetings/$meetingId/start',
    path: '/api/meetings/$meetingId/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStaffIdIndexRoute = ApiStaffIdIndexRouteImport.update({
  id: '/api/staff/$id/',
  path: '/api/staff/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIdHistoryRoute = ApiStudentsIdHistoryRouteImport.update({
  id: '/api/students/$id/history',
  path: '/api/students/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIdRecordsRoute = ApiStudentsIdRecordsRouteImport.update({
  id: '/api/students/$id/records',
  path: '/api/students/$id/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsImportResolveRoute =
  ApiStudentsImportResolveRouteImport.update({
    id: '/resolve',
    path: '/resolve',
    getParentRoute: () => ApiStudentsImportRoute,
  } as any)
const ApiMeetingsMeetingIdGeneralReportsIndexRoute =
  ApiMeetingsMeetingIdGeneralReportsIndexRouteImport.update({
    id: '/api/meetings/$meetingId/general-reports/',
    path: '/api/meetings/$meetingId/general-reports/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdGeneralReportsReportIdRoute =
  ApiMeetingsMeetingIdGeneralReportsReportIdRouteImport.update({
    id: '/api/meetings/$meetingId/general-reports/$reportId',
    path: '/api/meetings/$meetingId/general-reports/$reportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdMinutesIndexRoute =
  ApiMeetingsMeetingIdMinutesIndexRouteImport.update({
    id: '/api/meetings/$meetingId/minutes/',
    path: '/api/meetings/$meetingId/minutes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdMinutesApproveRoute =
  ApiMeetingsMeetingIdMinutesApproveRouteImport.update({
    id: '/api/meetings/$meetingId/minutes/approve',
    path: '/api/meetings/$meetingId/minutes/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdRecordsRecordIdRoute =
  ApiMeetingsMeetingIdRecordsRecordIdRouteImport.update({
    id: '/api/meetings/$meetingId/records/$recordId',
    path: '/api/meetings/$meetingId/records/$recordId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdClassesClassIdStudentsRoute =
  ApiMeetingsMeetingIdClassesClassIdStudentsRouteImport.update({
    id: '/api/meetings/$meetingId/classes/$classId/students',
    path: '/api/meetings/$meetingId/classes/$classId/students',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdMinutesVersionsIndexRoute =
  ApiMeetingsMeetingIdMinutesVersionsIndexRouteImport.update({
    id: '/api/meetings/$meetingId/minutes/versions/',
    path: '/api/meetings/$meetingId/minutes/versions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdStudentsStudentIdStatusRoute =
  ApiMeetingsMeetingIdStudentsStudentIdStatusRouteImport.update({
    id: '/api/meetings/$meetingId/students/$studentId/status',
    path: '/api/meetings/$meetingId/students/$studentId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute =
  ApiMeetingsMeetingIdMinutesVersionsVersionPdfRouteImport.update({
    id: '/api/meetings/$meetingId/minutes/versions/$version/pdf',
    path: '/api/meetings/$meetingId/minutes/versions/$version/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute =
  ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRouteImport.update({
    id: '/api/meetings/$meetingId/students/$studentId/records/',
    path: '/api/meetings/$meetingId/students/$studentId/records/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute =
  ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRouteImport.update(
    {
      id: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include',
      path: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/classes/enroll': typeof AppClassesEnrollRoute
  '/classes/new': typeof AppClassesNewRoute
  '/components/new': typeof AppComponentsNewRoute
  '/meetings/new': typeof AppMeetingsNewRoute
  '/roles/new': typeof AppRolesNewRoute
  '/staff/new': typeof AppStaffNewRoute
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/students/import': typeof ApiStudentsImportRouteWithChildren
  '/classes/': typeof AppClassesIndexRoute
  '/components/': typeof AppComponentsIndexRoute
  '/meetings/': typeof AppMeetingsIndexRoute
  '/roles/': typeof AppRolesIndexRoute
  '/staff/': typeof AppStaffIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/api/classes/': typeof ApiClassesIndexRoute
  '/api/components/': typeof ApiComponentsIndexRoute
  '/api/enrollments/': typeof ApiEnrollmentsIndexRoute
  '/api/meetings/': typeof ApiMeetingsIndexRoute
  '/api/minute-templates/': typeof ApiMinuteTemplatesIndexRoute
  '/api/roles/': typeof ApiRolesIndexRoute
  '/api/staff/': typeof ApiStaffIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/classes/$id/offers': typeof AppClassesIdOffersRoute
  '/classes/$id/students': typeof AppClassesIdStudentsRoute
  '/meetings/$meetingId/council': typeof AppMeetingsMeetingIdCouncilRoute
  '/meetings/$meetingId/participants': typeof AppMeetingsMeetingIdParticipantsRoute
  '/meetings/$meetingId/students': typeof AppMeetingsMeetingIdStudentsRoute
  '/api/classes/$id/history': typeof ApiClassesIdHistoryRoute
  '/api/classes/$id/offers': typeof ApiClassesIdOffersRoute
  '/api/classes/$id/students': typeof ApiClassesIdStudentsRoute
  '/api/meetings/$meetingId/finalize': typeof ApiMeetingsMeetingIdFinalizeRoute
  '/api/meetings/$meetingId/participants': typeof ApiMeetingsMeetingIdParticipantsRoute
  '/api/meetings/$meetingId/reopen': typeof ApiMeetingsMeetingIdReopenRoute
  '/api/meetings/$meetingId/start': typeof ApiMeetingsMeetingIdStartRoute
  '/api/students/$id/history': typeof ApiStudentsIdHistoryRoute
  '/api/students/$id/records': typeof ApiStudentsIdRecordsRoute
  '/api/students/import/resolve': typeof ApiStudentsImportResolveRoute
  '/meetings/$meetingId/': typeof AppMeetingsMeetingIdIndexRoute
  '/api/meetings/$meetingId/': typeof ApiMeetingsMeetingIdIndexRoute
  '/api/staff/$id/': typeof ApiStaffIdIndexRoute
  '/api/meetings/$meetingId/general-reports/$reportId': typeof ApiMeetingsMeetingIdGeneralReportsReportIdRoute
  '/api/meetings/$meetingId/minutes/approve': typeof ApiMeetingsMeetingIdMinutesApproveRoute
  '/api/meetings/$meetingId/records/$recordId': typeof ApiMeetingsMeetingIdRecordsRecordIdRoute
  '/api/meetings/$meetingId/general-reports/': typeof ApiMeetingsMeetingIdGeneralReportsIndexRoute
  '/api/meetings/$meetingId/minutes/': typeof ApiMeetingsMeetingIdMinutesIndexRoute
  '/api/meetings/$meetingId/classes/$classId/students': typeof ApiMeetingsMeetingIdClassesClassIdStudentsRoute
  '/api/meetings/$meetingId/students/$studentId/status': typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRoute
  '/api/meetings/$meetingId/minutes/versions/': typeof ApiMeetingsMeetingIdMinutesVersionsIndexRoute
  '/api/meetings/$meetingId/minutes/versions/$version/pdf': typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute
  '/api/meetings/$meetingId/students/$studentId/records/': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute
  '/api/meetings/$meetingId/students/$studentId/records/$recordId/include': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AppIndexRoute
  '/classes/enroll': typeof AppClassesEnrollRoute
  '/classes/new': typeof AppClassesNewRoute
  '/components/new': typeof AppComponentsNewRoute
  '/meetings/new': typeof AppMeetingsNewRoute
  '/roles/new': typeof AppRolesNewRoute
  '/staff/new': typeof AppStaffNewRoute
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/students/import': typeof ApiStudentsImportRouteWithChildren
  '/classes': typeof AppClassesIndexRoute
  '/components': typeof AppComponentsIndexRoute
  '/meetings': typeof AppMeetingsIndexRoute
  '/roles': typeof AppRolesIndexRoute
  '/staff': typeof AppStaffIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/api/classes': typeof ApiClassesIndexRoute
  '/api/components': typeof ApiComponentsIndexRoute
  '/api/enrollments': typeof ApiEnrollmentsIndexRoute
  '/api/meetings': typeof ApiMeetingsIndexRoute
  '/api/minute-templates': typeof ApiMinuteTemplatesIndexRoute
  '/api/roles': typeof ApiRolesIndexRoute
  '/api/staff': typeof ApiStaffIndexRoute
  '/api/students': typeof ApiStudentsIndexRoute
  '/classes/$id/offers': typeof AppClassesIdOffersRoute
  '/classes/$id/students': typeof AppClassesIdStudentsRoute
  '/meetings/$meetingId/council': typeof AppMeetingsMeetingIdCouncilRoute
  '/meetings/$meetingId/participants': typeof AppMeetingsMeetingIdParticipantsRoute
  '/meetings/$meetingId/students': typeof AppMeetingsMeetingIdStudentsRoute
  '/api/classes/$id/history': typeof ApiClassesIdHistoryRoute
  '/api/classes/$id/offers': typeof ApiClassesIdOffersRoute
  '/api/classes/$id/students': typeof ApiClassesIdStudentsRoute
  '/api/meetings/$meetingId/finalize': typeof ApiMeetingsMeetingIdFinalizeRoute
  '/api/meetings/$meetingId/participants': typeof ApiMeetingsMeetingIdParticipantsRoute
  '/api/meetings/$meetingId/reopen': typeof ApiMeetingsMeetingIdReopenRoute
  '/api/meetings/$meetingId/start': typeof ApiMeetingsMeetingIdStartRoute
  '/api/students/$id/history': typeof ApiStudentsIdHistoryRoute
  '/api/students/$id/records': typeof ApiStudentsIdRecordsRoute
  '/api/students/import/resolve': typeof ApiStudentsImportResolveRoute
  '/meetings/$meetingId': typeof AppMeetingsMeetingIdIndexRoute
  '/api/meetings/$meetingId': typeof ApiMeetingsMeetingIdIndexRoute
  '/api/staff/$id': typeof ApiStaffIdIndexRoute
  '/api/meetings/$meetingId/general-reports/$reportId': typeof ApiMeetingsMeetingIdGeneralReportsReportIdRoute
  '/api/meetings/$meetingId/minutes/approve': typeof ApiMeetingsMeetingIdMinutesApproveRoute
  '/api/meetings/$meetingId/records/$recordId': typeof ApiMeetingsMeetingIdRecordsRecordIdRoute
  '/api/meetings/$meetingId/general-reports': typeof ApiMeetingsMeetingIdGeneralReportsIndexRoute
  '/api/meetings/$meetingId/minutes': typeof ApiMeetingsMeetingIdMinutesIndexRoute
  '/api/meetings/$meetingId/classes/$classId/students': typeof ApiMeetingsMeetingIdClassesClassIdStudentsRoute
  '/api/meetings/$meetingId/students/$studentId/status': typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRoute
  '/api/meetings/$meetingId/minutes/versions': typeof ApiMeetingsMeetingIdMinutesVersionsIndexRoute
  '/api/meetings/$meetingId/minutes/versions/$version/pdf': typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute
  '/api/meetings/$meetingId/students/$studentId/records': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute
  '/api/meetings/$meetingId/students/$studentId/records/$recordId/include': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/classes/enroll': typeof AppClassesEnrollRoute
  '/_app/classes/new': typeof AppClassesNewRoute
  '/_app/components/new': typeof AppComponentsNewRoute
  '/_app/meetings/new': typeof AppMeetingsNewRoute
  '/_app/roles/new': typeof AppRolesNewRoute
  '/_app/staff/new': typeof AppStaffNewRoute
  '/_app/students/import': typeof AppStudentsImportRoute
  '/_app/students/new': typeof AppStudentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/students/import': typeof ApiStudentsImportRouteWithChildren
  '/_app/classes/': typeof AppClassesIndexRoute
  '/_app/components/': typeof AppComponentsIndexRoute
  '/_app/meetings/': typeof AppMeetingsIndexRoute
  '/_app/roles/': typeof AppRolesIndexRoute
  '/_app/staff/': typeof AppStaffIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/api/classes/': typeof ApiClassesIndexRoute
  '/api/components/': typeof ApiComponentsIndexRoute
  '/api/enrollments/': typeof ApiEnrollmentsIndexRoute
  '/api/meetings/': typeof ApiMeetingsIndexRoute
  '/api/minute-templates/': typeof ApiMinuteTemplatesIndexRoute
  '/api/roles/': typeof ApiRolesIndexRoute
  '/api/staff/': typeof ApiStaffIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/_app/classes/$id/offers': typeof AppClassesIdOffersRoute
  '/_app/classes/$id/students': typeof AppClassesIdStudentsRoute
  '/_app/meetings/$meetingId/council': typeof AppMeetingsMeetingIdCouncilRoute
  '/_app/meetings/$meetingId/participants': typeof AppMeetingsMeetingIdParticipantsRoute
  '/_app/meetings/$meetingId/students': typeof AppMeetingsMeetingIdStudentsRoute
  '/api/classes/$id/history': typeof ApiClassesIdHistoryRoute
  '/api/classes/$id/offers': typeof ApiClassesIdOffersRoute
  '/api/classes/$id/students': typeof ApiClassesIdStudentsRoute
  '/api/meetings/$meetingId/finalize': typeof ApiMeetingsMeetingIdFinalizeRoute
  '/api/meetings/$meetingId/participants': typeof ApiMeetingsMeetingIdParticipantsRoute
  '/api/meetings/$meetingId/reopen': typeof ApiMeetingsMeetingIdReopenRoute
  '/api/meetings/$meetingId/start': typeof ApiMeetingsMeetingIdStartRoute
  '/api/students/$id/history': typeof ApiStudentsIdHistoryRoute
  '/api/students/$id/records': typeof ApiStudentsIdRecordsRoute
  '/api/students/import/resolve': typeof ApiStudentsImportResolveRoute
  '/_app/meetings/$meetingId/': typeof AppMeetingsMeetingIdIndexRoute
  '/api/meetings/$meetingId/': typeof ApiMeetingsMeetingIdIndexRoute
  '/api/staff/$id/': typeof ApiStaffIdIndexRoute
  '/api/meetings/$meetingId/general-reports/$reportId': typeof ApiMeetingsMeetingIdGeneralReportsReportIdRoute
  '/api/meetings/$meetingId/minutes/approve': typeof ApiMeetingsMeetingIdMinutesApproveRoute
  '/api/meetings/$meetingId/records/$recordId': typeof ApiMeetingsMeetingIdRecordsRecordIdRoute
  '/api/meetings/$meetingId/general-reports/': typeof ApiMeetingsMeetingIdGeneralReportsIndexRoute
  '/api/meetings/$meetingId/minutes/': typeof ApiMeetingsMeetingIdMinutesIndexRoute
  '/api/meetings/$meetingId/classes/$classId/students': typeof ApiMeetingsMeetingIdClassesClassIdStudentsRoute
  '/api/meetings/$meetingId/students/$studentId/status': typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRoute
  '/api/meetings/$meetingId/minutes/versions/': typeof ApiMeetingsMeetingIdMinutesVersionsIndexRoute
  '/api/meetings/$meetingId/minutes/versions/$version/pdf': typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute
  '/api/meetings/$meetingId/students/$studentId/records/': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute
  '/api/meetings/$meetingId/students/$studentId/records/$recordId/include': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/classes/enroll'
    | '/classes/new'
    | '/components/new'
    | '/meetings/new'
    | '/roles/new'
    | '/staff/new'
    | '/students/import'
    | '/students/new'
    | '/api/auth/$'
    | '/api/students/import'
    | '/classes/'
    | '/components/'
    | '/meetings/'
    | '/roles/'
    | '/staff/'
    | '/students/'
    | '/api/classes/'
    | '/api/components/'
    | '/api/enrollments/'
    | '/api/meetings/'
    | '/api/minute-templates/'
    | '/api/roles/'
    | '/api/staff/'
    | '/api/students/'
    | '/classes/$id/offers'
    | '/classes/$id/students'
    | '/meetings/$meetingId/council'
    | '/meetings/$meetingId/participants'
    | '/meetings/$meetingId/students'
    | '/api/classes/$id/history'
    | '/api/classes/$id/offers'
    | '/api/classes/$id/students'
    | '/api/meetings/$meetingId/finalize'
    | '/api/meetings/$meetingId/participants'
    | '/api/meetings/$meetingId/reopen'
    | '/api/meetings/$meetingId/start'
    | '/api/students/$id/history'
    | '/api/students/$id/records'
    | '/api/students/import/resolve'
    | '/meetings/$meetingId/'
    | '/api/meetings/$meetingId/'
    | '/api/staff/$id/'
    | '/api/meetings/$meetingId/general-reports/$reportId'
    | '/api/meetings/$meetingId/minutes/approve'
    | '/api/meetings/$meetingId/records/$recordId'
    | '/api/meetings/$meetingId/general-reports/'
    | '/api/meetings/$meetingId/minutes/'
    | '/api/meetings/$meetingId/classes/$classId/students'
    | '/api/meetings/$meetingId/students/$studentId/status'
    | '/api/meetings/$meetingId/minutes/versions/'
    | '/api/meetings/$meetingId/minutes/versions/$version/pdf'
    | '/api/meetings/$meetingId/students/$studentId/records/'
    | '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/classes/enroll'
    | '/classes/new'
    | '/components/new'
    | '/meetings/new'
    | '/roles/new'
    | '/staff/new'
    | '/students/import'
    | '/students/new'
    | '/api/auth/$'
    | '/api/students/import'
    | '/classes'
    | '/components'
    | '/meetings'
    | '/roles'
    | '/staff'
    | '/students'
    | '/api/classes'
    | '/api/components'
    | '/api/enrollments'
    | '/api/meetings'
    | '/api/minute-templates'
    | '/api/roles'
    | '/api/staff'
    | '/api/students'
    | '/classes/$id/offers'
    | '/classes/$id/students'
    | '/meetings/$meetingId/council'
    | '/meetings/$meetingId/participants'
    | '/meetings/$meetingId/students'
    | '/api/classes/$id/history'
    | '/api/classes/$id/offers'
    | '/api/classes/$id/students'
    | '/api/meetings/$meetingId/finalize'
    | '/api/meetings/$meetingId/participants'
    | '/api/meetings/$meetingId/reopen'
    | '/api/meetings/$meetingId/start'
    | '/api/students/$id/history'
    | '/api/students/$id/records'
    | '/api/students/import/resolve'
    | '/meetings/$meetingId'
    | '/api/meetings/$meetingId'
    | '/api/staff/$id'
    | '/api/meetings/$meetingId/general-reports/$reportId'
    | '/api/meetings/$meetingId/minutes/approve'
    | '/api/meetings/$meetingId/records/$recordId'
    | '/api/meetings/$meetingId/general-reports'
    | '/api/meetings/$meetingId/minutes'
    | '/api/meetings/$meetingId/classes/$classId/students'
    | '/api/meetings/$meetingId/students/$studentId/status'
    | '/api/meetings/$meetingId/minutes/versions'
    | '/api/meetings/$meetingId/minutes/versions/$version/pdf'
    | '/api/meetings/$meetingId/students/$studentId/records'
    | '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/'
    | '/_app/classes/enroll'
    | '/_app/classes/new'
    | '/_app/components/new'
    | '/_app/meetings/new'
    | '/_app/roles/new'
    | '/_app/staff/new'
    | '/_app/students/import'
    | '/_app/students/new'
    | '/api/auth/$'
    | '/api/students/import'
    | '/_app/classes/'
    | '/_app/components/'
    | '/_app/meetings/'
    | '/_app/roles/'
    | '/_app/staff/'
    | '/_app/students/'
    | '/api/classes/'
    | '/api/components/'
    | '/api/enrollments/'
    | '/api/meetings/'
    | '/api/minute-templates/'
    | '/api/roles/'
    | '/api/staff/'
    | '/api/students/'
    | '/_app/classes/$id/offers'
    | '/_app/classes/$id/students'
    | '/_app/meetings/$meetingId/council'
    | '/_app/meetings/$meetingId/participants'
    | '/_app/meetings/$meetingId/students'
    | '/api/classes/$id/history'
    | '/api/classes/$id/offers'
    | '/api/classes/$id/students'
    | '/api/meetings/$meetingId/finalize'
    | '/api/meetings/$meetingId/participants'
    | '/api/meetings/$meetingId/reopen'
    | '/api/meetings/$meetingId/start'
    | '/api/students/$id/history'
    | '/api/students/$id/records'
    | '/api/students/import/resolve'
    | '/_app/meetings/$meetingId/'
    | '/api/meetings/$meetingId/'
    | '/api/staff/$id/'
    | '/api/meetings/$meetingId/general-reports/$reportId'
    | '/api/meetings/$meetingId/minutes/approve'
    | '/api/meetings/$meetingId/records/$recordId'
    | '/api/meetings/$meetingId/general-reports/'
    | '/api/meetings/$meetingId/minutes/'
    | '/api/meetings/$meetingId/classes/$classId/students'
    | '/api/meetings/$meetingId/students/$studentId/status'
    | '/api/meetings/$meetingId/minutes/versions/'
    | '/api/meetings/$meetingId/minutes/versions/$version/pdf'
    | '/api/meetings/$meetingId/students/$studentId/records/'
    | '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStudentsImportRoute: typeof ApiStudentsImportRouteWithChildren
  ApiClassesIndexRoute: typeof ApiClassesIndexRoute
  ApiComponentsIndexRoute: typeof ApiComponentsIndexRoute
  ApiEnrollmentsIndexRoute: typeof ApiEnrollmentsIndexRoute
  ApiMeetingsIndexRoute: typeof ApiMeetingsIndexRoute
  ApiMinuteTemplatesIndexRoute: typeof ApiMinuteTemplatesIndexRoute
  ApiRolesIndexRoute: typeof ApiRolesIndexRoute
  ApiStaffIndexRoute: typeof ApiStaffIndexRoute
  ApiStudentsIndexRoute: typeof ApiStudentsIndexRoute
  ApiClassesIdHistoryRoute: typeof ApiClassesIdHistoryRoute
  ApiClassesIdOffersRoute: typeof ApiClassesIdOffersRoute
  ApiClassesIdStudentsRoute: typeof ApiClassesIdStudentsRoute
  ApiMeetingsMeetingIdFinalizeRoute: typeof ApiMeetingsMeetingIdFinalizeRoute
  ApiMeetingsMeetingIdParticipantsRoute: typeof ApiMeetingsMeetingIdParticipantsRoute
  ApiMeetingsMeetingIdReopenRoute: typeof ApiMeetingsMeetingIdReopenRoute
  ApiMeetingsMeetingIdStartRoute: typeof ApiMeetingsMeetingIdStartRoute
  ApiStudentsIdHistoryRoute: typeof ApiStudentsIdHistoryRoute
  ApiStudentsIdRecordsRoute: typeof ApiStudentsIdRecordsRoute
  ApiMeetingsMeetingIdIndexRoute: typeof ApiMeetingsMeetingIdIndexRoute
  ApiStaffIdIndexRoute: typeof ApiStaffIdIndexRoute
  ApiMeetingsMeetingIdGeneralReportsReportIdRoute: typeof ApiMeetingsMeetingIdGeneralReportsReportIdRoute
  ApiMeetingsMeetingIdMinutesApproveRoute: typeof ApiMeetingsMeetingIdMinutesApproveRoute
  ApiMeetingsMeetingIdRecordsRecordIdRoute: typeof ApiMeetingsMeetingIdRecordsRecordIdRoute
  ApiMeetingsMeetingIdGeneralReportsIndexRoute: typeof ApiMeetingsMeetingIdGeneralReportsIndexRoute
  ApiMeetingsMeetingIdMinutesIndexRoute: typeof ApiMeetingsMeetingIdMinutesIndexRoute
  ApiMeetingsMeetingIdClassesClassIdStudentsRoute: typeof ApiMeetingsMeetingIdClassesClassIdStudentsRoute
  ApiMeetingsMeetingIdStudentsStudentIdStatusRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRoute
  ApiMeetingsMeetingIdMinutesVersionsIndexRoute: typeof ApiMeetingsMeetingIdMinutesVersionsIndexRoute
  ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute: typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute
  ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute
  ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/classes/': {
      id: '/_app/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AppClassesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/classes/enroll': {
      id: '/_app/classes/enroll'
      path: '/classes/enroll'
      fullPath: '/classes/enroll'
      preLoaderRoute: typeof AppClassesEnrollRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/classes/new': {
      id: '/_app/classes/new'
      path: '/classes/new'
      fullPath: '/classes/new'
      preLoaderRoute: typeof AppClassesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/components/': {
      id: '/_app/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof AppComponentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/components/new': {
      id: '/_app/components/new'
      path: '/components/new'
      fullPath: '/components/new'
      preLoaderRoute: typeof AppComponentsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/': {
      id: '/_app/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AppMeetingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/new': {
      id: '/_app/meetings/new'
      path: '/meetings/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof AppMeetingsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles/new': {
      id: '/_app/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AppRolesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/staff/new': {
      id: '/_app/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof AppStaffNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students/import': {
      id: '/_app/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AppStudentsImportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students/new': {
      id: '/_app/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/': {
      id: '/api/classes/'
      path: '/api/classes'
      fullPath: '/api/classes/'
      preLoaderRoute: typeof ApiClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/components/': {
      id: '/api/components/'
      path: '/api/components'
      fullPath: '/api/components/'
      preLoaderRoute: typeof ApiComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrollments/': {
      id: '/api/enrollments/'
      path: '/api/enrollments'
      fullPath: '/api/enrollments/'
      preLoaderRoute: typeof ApiEnrollmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/': {
      id: '/api/meetings/'
      path: '/api/meetings'
      fullPath: '/api/meetings/'
      preLoaderRoute: typeof ApiMeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/minute-templates/': {
      id: '/api/minute-templates/'
      path: '/api/minute-templates'
      fullPath: '/api/minute-templates/'
      preLoaderRoute: typeof ApiMinuteTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roles/': {
      id: '/api/roles/'
      path: '/api/roles'
      fullPath: '/api/roles/'
      preLoaderRoute: typeof ApiRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/': {
      id: '/api/staff/'
      path: '/api/staff'
      fullPath: '/api/staff/'
      preLoaderRoute: typeof ApiStaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/': {
      id: '/api/students/'
      path: '/api/students'
      fullPath: '/api/students/'
      preLoaderRoute: typeof ApiStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/import': {
      id: '/api/students/import'
      path: '/api/students/import'
      fullPath: '/api/students/import'
      preLoaderRoute: typeof ApiStudentsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/classes/$id/offers': {
      id: '/_app/classes/$id/offers'
      path: '/classes/$id/offers'
      fullPath: '/classes/$id/offers'
      preLoaderRoute: typeof AppClassesIdOffersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/classes/$id/students': {
      id: '/_app/classes/$id/students'
      path: '/classes/$id/students'
      fullPath: '/classes/$id/students'
      preLoaderRoute: typeof AppClassesIdStudentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/$meetingId/': {
      id: '/_app/meetings/$meetingId/'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId/'
      preLoaderRoute: typeof AppMeetingsMeetingIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/$meetingId/council': {
      id: '/_app/meetings/$meetingId/council'
      path: '/meetings/$meetingId/council'
      fullPath: '/meetings/$meetingId/council'
      preLoaderRoute: typeof AppMeetingsMeetingIdCouncilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/$meetingId/participants': {
      id: '/_app/meetings/$meetingId/participants'
      path: '/meetings/$meetingId/participants'
      fullPath: '/meetings/$meetingId/participants'
      preLoaderRoute: typeof AppMeetingsMeetingIdParticipantsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/$meetingId/students': {
      id: '/_app/meetings/$meetingId/students'
      path: '/meetings/$meetingId/students'
      fullPath: '/meetings/$meetingId/students'
      preLoaderRoute: typeof AppMeetingsMeetingIdStudentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/classes/$id/history': {
      id: '/api/classes/$id/history'
      path: '/api/classes/$id/history'
      fullPath: '/api/classes/$id/history'
      preLoaderRoute: typeof ApiClassesIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/$id/offers': {
      id: '/api/classes/$id/offers'
      path: '/api/classes/$id/offers'
      fullPath: '/api/classes/$id/offers'
      preLoaderRoute: typeof ApiClassesIdOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/$id/students': {
      id: '/api/classes/$id/students'
      path: '/api/classes/$id/students'
      fullPath: '/api/classes/$id/students'
      preLoaderRoute: typeof ApiClassesIdStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/': {
      id: '/api/meetings/$meetingId/'
      path: '/api/meetings/$meetingId'
      fullPath: '/api/meetings/$meetingId/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/finalize': {
      id: '/api/meetings/$meetingId/finalize'
      path: '/api/meetings/$meetingId/finalize'
      fullPath: '/api/meetings/$meetingId/finalize'
      preLoaderRoute: typeof ApiMeetingsMeetingIdFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/participants': {
      id: '/api/meetings/$meetingId/participants'
      path: '/api/meetings/$meetingId/participants'
      fullPath: '/api/meetings/$meetingId/participants'
      preLoaderRoute: typeof ApiMeetingsMeetingIdParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/reopen': {
      id: '/api/meetings/$meetingId/reopen'
      path: '/api/meetings/$meetingId/reopen'
      fullPath: '/api/meetings/$meetingId/reopen'
      preLoaderRoute: typeof ApiMeetingsMeetingIdReopenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/start': {
      id: '/api/meetings/$meetingId/start'
      path: '/api/meetings/$meetingId/start'
      fullPath: '/api/meetings/$meetingId/start'
      preLoaderRoute: typeof ApiMeetingsMeetingIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/$id/': {
      id: '/api/staff/$id/'
      path: '/api/staff/$id'
      fullPath: '/api/staff/$id/'
      preLoaderRoute: typeof ApiStaffIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/$id/history': {
      id: '/api/students/$id/history'
      path: '/api/students/$id/history'
      fullPath: '/api/students/$id/history'
      preLoaderRoute: typeof ApiStudentsIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/$id/records': {
      id: '/api/students/$id/records'
      path: '/api/students/$id/records'
      fullPath: '/api/students/$id/records'
      preLoaderRoute: typeof ApiStudentsIdRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/import/resolve': {
      id: '/api/students/import/resolve'
      path: '/resolve'
      fullPath: '/api/students/import/resolve'
      preLoaderRoute: typeof ApiStudentsImportResolveRouteImport
      parentRoute: typeof ApiStudentsImportRoute
    }
    '/api/meetings/$meetingId/general-reports/': {
      id: '/api/meetings/$meetingId/general-reports/'
      path: '/api/meetings/$meetingId/general-reports'
      fullPath: '/api/meetings/$meetingId/general-reports/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdGeneralReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/general-reports/$reportId': {
      id: '/api/meetings/$meetingId/general-reports/$reportId'
      path: '/api/meetings/$meetingId/general-reports/$reportId'
      fullPath: '/api/meetings/$meetingId/general-reports/$reportId'
      preLoaderRoute: typeof ApiMeetingsMeetingIdGeneralReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/minutes/': {
      id: '/api/meetings/$meetingId/minutes/'
      path: '/api/meetings/$meetingId/minutes'
      fullPath: '/api/meetings/$meetingId/minutes/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdMinutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/minutes/approve': {
      id: '/api/meetings/$meetingId/minutes/approve'
      path: '/api/meetings/$meetingId/minutes/approve'
      fullPath: '/api/meetings/$meetingId/minutes/approve'
      preLoaderRoute: typeof ApiMeetingsMeetingIdMinutesApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/records/$recordId': {
      id: '/api/meetings/$meetingId/records/$recordId'
      path: '/api/meetings/$meetingId/records/$recordId'
      fullPath: '/api/meetings/$meetingId/records/$recordId'
      preLoaderRoute: typeof ApiMeetingsMeetingIdRecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/classes/$classId/students': {
      id: '/api/meetings/$meetingId/classes/$classId/students'
      path: '/api/meetings/$meetingId/classes/$classId/students'
      fullPath: '/api/meetings/$meetingId/classes/$classId/students'
      preLoaderRoute: typeof ApiMeetingsMeetingIdClassesClassIdStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/minutes/versions/': {
      id: '/api/meetings/$meetingId/minutes/versions/'
      path: '/api/meetings/$meetingId/minutes/versions'
      fullPath: '/api/meetings/$meetingId/minutes/versions/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdMinutesVersionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/students/$studentId/status': {
      id: '/api/meetings/$meetingId/students/$studentId/status'
      path: '/api/meetings/$meetingId/students/$studentId/status'
      fullPath: '/api/meetings/$meetingId/students/$studentId/status'
      preLoaderRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/minutes/versions/$version/pdf': {
      id: '/api/meetings/$meetingId/minutes/versions/$version/pdf'
      path: '/api/meetings/$meetingId/minutes/versions/$version/pdf'
      fullPath: '/api/meetings/$meetingId/minutes/versions/$version/pdf'
      preLoaderRoute: typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/students/$studentId/records/': {
      id: '/api/meetings/$meetingId/students/$studentId/records/'
      path: '/api/meetings/$meetingId/students/$studentId/records'
      fullPath: '/api/meetings/$meetingId/students/$studentId/records/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/students/$studentId/records/$recordId/include': {
      id: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
      path: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
      fullPath: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
      preLoaderRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClassesEnrollRoute: typeof AppClassesEnrollRoute
  AppClassesNewRoute: typeof AppClassesNewRoute
  AppComponentsNewRoute: typeof AppComponentsNewRoute
  AppMeetingsNewRoute: typeof AppMeetingsNewRoute
  AppRolesNewRoute: typeof AppRolesNewRoute
  AppStaffNewRoute: typeof AppStaffNewRoute
  AppStudentsImportRoute: typeof AppStudentsImportRoute
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppClassesIndexRoute: typeof AppClassesIndexRoute
  AppComponentsIndexRoute: typeof AppComponentsIndexRoute
  AppMeetingsIndexRoute: typeof AppMeetingsIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppClassesIdOffersRoute: typeof AppClassesIdOffersRoute
  AppClassesIdStudentsRoute: typeof AppClassesIdStudentsRoute
  AppMeetingsMeetingIdCouncilRoute: typeof AppMeetingsMeetingIdCouncilRoute
  AppMeetingsMeetingIdParticipantsRoute: typeof AppMeetingsMeetingIdParticipantsRoute
  AppMeetingsMeetingIdStudentsRoute: typeof AppMeetingsMeetingIdStudentsRoute
  AppMeetingsMeetingIdIndexRoute: typeof AppMeetingsMeetingIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClassesEnrollRoute: AppClassesEnrollRoute,
  AppClassesNewRoute: AppClassesNewRoute,
  AppComponentsNewRoute: AppComponentsNewRoute,
  AppMeetingsNewRoute: AppMeetingsNewRoute,
  AppRolesNewRoute: AppRolesNewRoute,
  AppStaffNewRoute: AppStaffNewRoute,
  AppStudentsImportRoute: AppStudentsImportRoute,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppClassesIndexRoute: AppClassesIndexRoute,
  AppComponentsIndexRoute: AppComponentsIndexRoute,
  AppMeetingsIndexRoute: AppMeetingsIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppClassesIdOffersRoute: AppClassesIdOffersRoute,
  AppClassesIdStudentsRoute: AppClassesIdStudentsRoute,
  AppMeetingsMeetingIdCouncilRoute: AppMeetingsMeetingIdCouncilRoute,
  AppMeetingsMeetingIdParticipantsRoute: AppMeetingsMeetingIdParticipantsRoute,
  AppMeetingsMeetingIdStudentsRoute: AppMeetingsMeetingIdStudentsRoute,
  AppMeetingsMeetingIdIndexRoute: AppMeetingsMeetingIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ApiStudentsImportRouteChildren {
  ApiStudentsImportResolveRoute: typeof ApiStudentsImportResolveRoute
}

const ApiStudentsImportRouteChildren: ApiStudentsImportRouteChildren = {
  ApiStudentsImportResolveRoute: ApiStudentsImportResolveRoute,
}

const ApiStudentsImportRouteWithChildren =
  ApiStudentsImportRoute._addFileChildren(ApiStudentsImportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStudentsImportRoute: ApiStudentsImportRouteWithChildren,
  ApiClassesIndexRoute: ApiClassesIndexRoute,
  ApiComponentsIndexRoute: ApiComponentsIndexRoute,
  ApiEnrollmentsIndexRoute: ApiEnrollmentsIndexRoute,
  ApiMeetingsIndexRoute: ApiMeetingsIndexRoute,
  ApiMinuteTemplatesIndexRoute: ApiMinuteTemplatesIndexRoute,
  ApiRolesIndexRoute: ApiRolesIndexRoute,
  ApiStaffIndexRoute: ApiStaffIndexRoute,
  ApiStudentsIndexRoute: ApiStudentsIndexRoute,
  ApiClassesIdHistoryRoute: ApiClassesIdHistoryRoute,
  ApiClassesIdOffersRoute: ApiClassesIdOffersRoute,
  ApiClassesIdStudentsRoute: ApiClassesIdStudentsRoute,
  ApiMeetingsMeetingIdFinalizeRoute: ApiMeetingsMeetingIdFinalizeRoute,
  ApiMeetingsMeetingIdParticipantsRoute: ApiMeetingsMeetingIdParticipantsRoute,
  ApiMeetingsMeetingIdReopenRoute: ApiMeetingsMeetingIdReopenRoute,
  ApiMeetingsMeetingIdStartRoute: ApiMeetingsMeetingIdStartRoute,
  ApiStudentsIdHistoryRoute: ApiStudentsIdHistoryRoute,
  ApiStudentsIdRecordsRoute: ApiStudentsIdRecordsRoute,
  ApiMeetingsMeetingIdIndexRoute: ApiMeetingsMeetingIdIndexRoute,
  ApiStaffIdIndexRoute: ApiStaffIdIndexRoute,
  ApiMeetingsMeetingIdGeneralReportsReportIdRoute:
    ApiMeetingsMeetingIdGeneralReportsReportIdRoute,
  ApiMeetingsMeetingIdMinutesApproveRoute:
    ApiMeetingsMeetingIdMinutesApproveRoute,
  ApiMeetingsMeetingIdRecordsRecordIdRoute:
    ApiMeetingsMeetingIdRecordsRecordIdRoute,
  ApiMeetingsMeetingIdGeneralReportsIndexRoute:
    ApiMeetingsMeetingIdGeneralReportsIndexRoute,
  ApiMeetingsMeetingIdMinutesIndexRoute: ApiMeetingsMeetingIdMinutesIndexRoute,
  ApiMeetingsMeetingIdClassesClassIdStudentsRoute:
    ApiMeetingsMeetingIdClassesClassIdStudentsRoute,
  ApiMeetingsMeetingIdStudentsStudentIdStatusRoute:
    ApiMeetingsMeetingIdStudentsStudentIdStatusRoute,
  ApiMeetingsMeetingIdMinutesVersionsIndexRoute:
    ApiMeetingsMeetingIdMinutesVersionsIndexRoute,
  ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute:
    ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute,
  ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute:
    ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute,
  ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute:
    ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
