/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students/index'
import { Route as AppStudentsImportRouteImport } from './routes/_app/students/import'
import { Route as AppStudentsNewRouteImport } from './routes/_app/students/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStudentsIndexRouteImport } from './routes/api/students/index'
import { Route as ApiStudentsImportRouteImport } from './routes/api/students/import'
import { Route as ApiStudentsImportResolveRouteImport } from './routes/api/students/import.resolve'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsImportRoute = AppStudentsImportRouteImport.update({
  id: '/students/import',
  path: '/students/import',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIndexRoute = ApiStudentsIndexRouteImport.update({
  id: '/api/students/',
  path: '/api/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsImportRoute = ApiStudentsImportRouteImport.update({
  id: '/api/students/import',
  path: '/api/students/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsImportResolveRoute =
  ApiStudentsImportResolveRouteImport.update({
    id: '/resolve',
    path: '/resolve',
    getParentRoute: () => ApiStudentsImportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/students/import': typeof ApiStudentsImportRouteWithChildren
  '/students/': typeof AppStudentsIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/api/students/import/resolve': typeof ApiStudentsImportResolveRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AppIndexRoute
  '/students/import': typeof AppStudentsImportRoute
  '/students/new': typeof AppStudentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/students/import': typeof ApiStudentsImportRouteWithChildren
  '/students': typeof AppStudentsIndexRoute
  '/api/students': typeof ApiStudentsIndexRoute
  '/api/students/import/resolve': typeof ApiStudentsImportResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/students/import': typeof AppStudentsImportRoute
  '/_app/students/new': typeof AppStudentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/students/import': typeof ApiStudentsImportRouteWithChildren
  '/_app/students/': typeof AppStudentsIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/api/students/import/resolve': typeof ApiStudentsImportResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/students/import'
    | '/students/new'
    | '/api/auth/$'
    | '/api/students/import'
    | '/students/'
    | '/api/students/'
    | '/api/students/import/resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/students/import'
    | '/students/new'
    | '/api/auth/$'
    | '/api/students/import'
    | '/students'
    | '/api/students'
    | '/api/students/import/resolve'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/'
    | '/_app/students/import'
    | '/_app/students/new'
    | '/api/auth/$'
    | '/api/students/import'
    | '/_app/students/'
    | '/api/students/'
    | '/api/students/import/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStudentsImportRoute: typeof ApiStudentsImportRouteWithChildren
  ApiStudentsIndexRoute: typeof ApiStudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students/import': {
      id: '/_app/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AppStudentsImportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students/new': {
      id: '/_app/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/': {
      id: '/api/students/'
      path: '/api/students'
      fullPath: '/api/students/'
      preLoaderRoute: typeof ApiStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/import': {
      id: '/api/students/import'
      path: '/api/students/import'
      fullPath: '/api/students/import'
      preLoaderRoute: typeof ApiStudentsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/import/resolve': {
      id: '/api/students/import/resolve'
      path: '/resolve'
      fullPath: '/api/students/import/resolve'
      preLoaderRoute: typeof ApiStudentsImportResolveRouteImport
      parentRoute: typeof ApiStudentsImportRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppStudentsImportRoute: typeof AppStudentsImportRoute
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppStudentsImportRoute: AppStudentsImportRoute,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ApiStudentsImportRouteChildren {
  ApiStudentsImportResolveRoute: typeof ApiStudentsImportResolveRoute
}

const ApiStudentsImportRouteChildren: ApiStudentsImportRouteChildren = {
  ApiStudentsImportResolveRoute: ApiStudentsImportResolveRoute,
}

const ApiStudentsImportRouteWithChildren =
  ApiStudentsImportRoute._addFileChildren(ApiStudentsImportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStudentsImportRoute: ApiStudentsImportRouteWithChildren,
  ApiStudentsIndexRoute: ApiStudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
