/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppClassesIndexRouteImport } from './routes/_app/classes/index'
import { Route as AppClassesEnrollRouteImport } from './routes/_app/classes/enroll'
import { Route as AppComponentsIndexRouteImport } from './routes/_app/components/index'
import { Route as AppComponentsIdRouteImport } from './routes/_app/components/$id'
import { Route as AppMeetingsIndexRouteImport } from './routes/_app/meetings/index'
import { Route as AppMinutesIndexRouteImport } from './routes/_app/minutes/index'
import { Route as AppMinutesMeetingIdRouteImport } from './routes/_app/minutes/$meetingId'
import { Route as AppMinutesTemplatesRouteImport } from './routes/_app/minutes/templates'
import { Route as AppRolesIndexRouteImport } from './routes/_app/roles/index'
import { Route as AppRolesIdRouteImport } from './routes/_app/roles/$id'
import { Route as AppStaffIndexRouteImport } from './routes/_app/staff/index'
import { Route as AppStaffIdRouteImport } from './routes/_app/staff/$id'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students/index'
import { Route as AppStudentsIdRouteImport } from './routes/_app/students/$id'
import { Route as AppStudentsImportRouteImport } from './routes/_app/students/import'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiClassesIndexRouteImport } from './routes/api/classes/index'
import { Route as ApiComponentsIndexRouteImport } from './routes/api/components/index'
import { Route as ApiEnrollmentsIndexRouteImport } from './routes/api/enrollments/index'
import { Route as ApiInvitationsIndexRouteImport } from './routes/api/invitations/index'
import { Route as ApiInvitationsStatusRouteImport } from './routes/api/invitations/status'
import { Route as ApiInvitationsVerifyRouteImport } from './routes/api/invitations/verify'
import { Route as ApiMeetingsIndexRouteImport } from './routes/api/meetings/index'
import { Route as ApiMinuteTemplatesIndexRouteImport } from './routes/api/minute-templates/index'
import { Route as ApiMinutesIndexRouteImport } from './routes/api/minutes/index'
import { Route as ApiRolesIndexRouteImport } from './routes/api/roles/index'
import { Route as ApiStaffIndexRouteImport } from './routes/api/staff/index'
import { Route as ApiStudentsIndexRouteImport } from './routes/api/students/index'
import { Route as ApiStudentsImportRouteImport } from './routes/api/students/import'
import { Route as AppClassesIdOffersRouteImport } from './routes/_app/classes/$id/offers'
import { Route as AppClassesIdStudentsRouteImport } from './routes/_app/classes/$id/students'
import { Route as AppMeetingsMeetingIdIndexRouteImport } from './routes/_app/meetings/$meetingId/index'
import { Route as AppMeetingsMeetingIdCouncilRouteImport } from './routes/_app/meetings/$meetingId/council'
import { Route as AppMeetingsMeetingIdParticipantsRouteImport } from './routes/_app/meetings/$meetingId/participants'
import { Route as AppMeetingsMeetingIdStudentsRouteImport } from './routes/_app/meetings/$meetingId/students'
import { Route as AppMinutesTemplatesIndexRouteImport } from './routes/_app/minutes/templates/index'
import { Route as AppMinutesTemplatesIdRouteImport } from './routes/_app/minutes/templates/$id'
import { Route as ApiAdminUsersIndexRouteImport } from './routes/api/admin/users/index'
import { Route as ApiClassesIdIndexRouteImport } from './routes/api/classes/$id/index'
import { Route as ApiClassesIdHistoryRouteImport } from './routes/api/classes/$id/history'
import { Route as ApiClassesIdOffersRouteImport } from './routes/api/classes/$id/offers'
import { Route as ApiClassesIdStudentsRouteImport } from './routes/api/classes/$id/students'
import { Route as ApiComponentsIdIndexRouteImport } from './routes/api/components/$id/index'
import { Route as ApiInvitationsIdIndexRouteImport } from './routes/api/invitations/$id/index'
import { Route as ApiMeetingsMeetingIdIndexRouteImport } from './routes/api/meetings/$meetingId/index'
import { Route as ApiMeetingsMeetingIdParticipantsRouteImport } from './routes/api/meetings/$meetingId/participants'
import { Route as ApiMeetingsMeetingIdReopenRouteImport } from './routes/api/meetings/$meetingId/reopen'
import { Route as ApiMinuteTemplatesIdIndexRouteImport } from './routes/api/minute-templates/$id/index'
import { Route as ApiRolesIdIndexRouteImport } from './routes/api/roles/$id/index'
import { Route as ApiStaffIdIndexRouteImport } from './routes/api/staff/$id/index'
import { Route as ApiStudentsIdIndexRouteImport } from './routes/api/students/$id/index'
import { Route as ApiStudentsIdHistoryRouteImport } from './routes/api/students/$id/history'
import { Route as ApiStudentsIdRecordsRouteImport } from './routes/api/students/$id/records'
import { Route as ApiStudentsImportResolveRouteImport } from './routes/api/students/import.resolve'
import { Route as ApiAdminUsersIdIndexRouteImport } from './routes/api/admin/users/$id/index'
import { Route as ApiMeetingsMeetingIdClassesIndexRouteImport } from './routes/api/meetings/$meetingId/classes/index'
import { Route as ApiMeetingsMeetingIdGeneralReportsIndexRouteImport } from './routes/api/meetings/$meetingId/general-reports/index'
import { Route as ApiMeetingsMeetingIdGeneralReportsReportIdRouteImport } from './routes/api/meetings/$meetingId/general-reports/$reportId'
import { Route as ApiMeetingsMeetingIdMinutesIndexRouteImport } from './routes/api/meetings/$meetingId/minutes/index'
import { Route as ApiMeetingsMeetingIdMinutesApproveRouteImport } from './routes/api/meetings/$meetingId/minutes/approve'
import { Route as ApiMeetingsMeetingIdMinutesContentRouteImport } from './routes/api/meetings/$meetingId/minutes/content'
import { Route as ApiMeetingsMeetingIdRecordsRecordIdRouteImport } from './routes/api/meetings/$meetingId/records/$recordId'
import { Route as ApiMeetingsMeetingIdClassesClassIdIndexRouteImport } from './routes/api/meetings/$meetingId/classes/$classId/index'
import { Route as ApiMeetingsMeetingIdClassesClassIdStudentsRouteImport } from './routes/api/meetings/$meetingId/classes/$classId/students'
import { Route as ApiMeetingsMeetingIdMinutesVersionsIndexRouteImport } from './routes/api/meetings/$meetingId/minutes/versions/index'
import { Route as ApiMeetingsMeetingIdStudentsStudentIdStatusRouteImport } from './routes/api/meetings/$meetingId/students/$studentId/status'
import { Route as ApiMeetingsMeetingIdMinutesVersionsVersionPdfRouteImport } from './routes/api/meetings/$meetingId/minutes/versions/$version/pdf'
import { Route as ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRouteImport } from './routes/api/meetings/$meetingId/students/$studentId/records/index'
import { Route as ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRouteImport } from './routes/api/meetings/$meetingId/students/$studentId/records/$recordId/include'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppClassesIndexRoute = AppClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClassesEnrollRoute = AppClassesEnrollRouteImport.update({
  id: '/classes/enroll',
  path: '/classes/enroll',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComponentsIndexRoute = AppComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComponentsIdRoute = AppComponentsIdRouteImport.update({
  id: '/components/$id',
  path: '/components/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsIndexRoute = AppMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMinutesIndexRoute = AppMinutesIndexRouteImport.update({
  id: '/minutes/',
  path: '/minutes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMinutesMeetingIdRoute = AppMinutesMeetingIdRouteImport.update({
  id: '/minutes/$meetingId',
  path: '/minutes/$meetingId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMinutesTemplatesRoute = AppMinutesTemplatesRouteImport.update({
  id: '/minutes/templates',
  path: '/minutes/templates',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesIdRoute = AppRolesIdRouteImport.update({
  id: '/roles/$id',
  path: '/roles/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStaffIdRoute = AppStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsImportRoute = AppStudentsImportRouteImport.update({
  id: '/students/import',
  path: '/students/import',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesIndexRoute = ApiClassesIndexRouteImport.update({
  id: '/api/classes/',
  path: '/api/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComponentsIndexRoute = ApiComponentsIndexRouteImport.update({
  id: '/api/components/',
  path: '/api/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrollmentsIndexRoute = ApiEnrollmentsIndexRouteImport.update({
  id: '/api/enrollments/',
  path: '/api/enrollments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsIndexRoute = ApiInvitationsIndexRouteImport.update({
  id: '/api/invitations/',
  path: '/api/invitations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsStatusRoute = ApiInvitationsStatusRouteImport.update({
  id: '/api/invitations/status',
  path: '/api/invitations/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsVerifyRoute = ApiInvitationsVerifyRouteImport.update({
  id: '/api/invitations/verify',
  path: '/api/invitations/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsIndexRoute = ApiMeetingsIndexRouteImport.update({
  id: '/api/meetings/',
  path: '/api/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMinuteTemplatesIndexRoute = ApiMinuteTemplatesIndexRouteImport.update({
  id: '/api/minute-templates/',
  path: '/api/minute-templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMinutesIndexRoute = ApiMinutesIndexRouteImport.update({
  id: '/api/minutes/',
  path: '/api/minutes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRolesIndexRoute = ApiRolesIndexRouteImport.update({
  id: '/api/roles/',
  path: '/api/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffIndexRoute = ApiStaffIndexRouteImport.update({
  id: '/api/staff/',
  path: '/api/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIndexRoute = ApiStudentsIndexRouteImport.update({
  id: '/api/students/',
  path: '/api/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsImportRoute = ApiStudentsImportRouteImport.update({
  id: '/api/students/import',
  path: '/api/students/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClassesIdOffersRoute = AppClassesIdOffersRouteImport.update({
  id: '/classes/$id/offers',
  path: '/classes/$id/offers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClassesIdStudentsRoute = AppClassesIdStudentsRouteImport.update({
  id: '/classes/$id/students',
  path: '/classes/$id/students',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsMeetingIdIndexRoute =
  AppMeetingsMeetingIdIndexRouteImport.update({
    id: '/meetings/$meetingId/',
    path: '/meetings/$meetingId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMeetingsMeetingIdCouncilRoute =
  AppMeetingsMeetingIdCouncilRouteImport.update({
    id: '/meetings/$meetingId/council',
    path: '/meetings/$meetingId/council',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMeetingsMeetingIdParticipantsRoute =
  AppMeetingsMeetingIdParticipantsRouteImport.update({
    id: '/meetings/$meetingId/participants',
    path: '/meetings/$meetingId/participants',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMeetingsMeetingIdStudentsRoute =
  AppMeetingsMeetingIdStudentsRouteImport.update({
    id: '/meetings/$meetingId/students',
    path: '/meetings/$meetingId/students',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMinutesTemplatesIndexRoute =
  AppMinutesTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppMinutesTemplatesRoute,
  } as any)
const AppMinutesTemplatesIdRoute = AppMinutesTemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMinutesTemplatesRoute,
} as any)
const ApiAdminUsersIndexRoute = ApiAdminUsersIndexRouteImport.update({
  id: '/api/admin/users/',
  path: '/api/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesIdIndexRoute = ApiClassesIdIndexRouteImport.update({
  id: '/api/classes/$id/',
  path: '/api/classes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesIdHistoryRoute = ApiClassesIdHistoryRouteImport.update({
  id: '/api/classes/$id/history',
  path: '/api/classes/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesIdOffersRoute = ApiClassesIdOffersRouteImport.update({
  id: '/api/classes/$id/offers',
  path: '/api/classes/$id/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesIdStudentsRoute = ApiClassesIdStudentsRouteImport.update({
  id: '/api/classes/$id/students',
  path: '/api/classes/$id/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComponentsIdIndexRoute = ApiComponentsIdIndexRouteImport.update({
  id: '/api/components/$id/',
  path: '/api/components/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsIdIndexRoute = ApiInvitationsIdIndexRouteImport.update({
  id: '/api/invitations/$id/',
  path: '/api/invitations/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsMeetingIdIndexRoute =
  ApiMeetingsMeetingIdIndexRouteImport.update({
    id: '/api/meetings/$meetingId/',
    path: '/api/meetings/$meetingId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdParticipantsRoute =
  ApiMeetingsMeetingIdParticipantsRouteImport.update({
    id: '/api/meetings/$meetingId/participants',
    path: '/api/meetings/$meetingId/participants',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdReopenRoute =
  ApiMeetingsMeetingIdReopenRouteImport.update({
    id: '/api/meetings/$meetingId/reopen',
    path: '/api/meetings/$meetingId/reopen',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMinuteTemplatesIdIndexRoute =
  ApiMinuteTemplatesIdIndexRouteImport.update({
    id: '/api/minute-templates/$id/',
    path: '/api/minute-templates/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRolesIdIndexRoute = ApiRolesIdIndexRouteImport.update({
  id: '/api/roles/$id/',
  path: '/api/roles/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffIdIndexRoute = ApiStaffIdIndexRouteImport.update({
  id: '/api/staff/$id/',
  path: '/api/staff/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIdIndexRoute = ApiStudentsIdIndexRouteImport.update({
  id: '/api/students/$id/',
  path: '/api/students/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIdHistoryRoute = ApiStudentsIdHistoryRouteImport.update({
  id: '/api/students/$id/history',
  path: '/api/students/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIdRecordsRoute = ApiStudentsIdRecordsRouteImport.update({
  id: '/api/students/$id/records',
  path: '/api/students/$id/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsImportResolveRoute =
  ApiStudentsImportResolveRouteImport.update({
    id: '/resolve',
    path: '/resolve',
    getParentRoute: () => ApiStudentsImportRoute,
  } as any)
const ApiAdminUsersIdIndexRoute = ApiAdminUsersIdIndexRouteImport.update({
  id: '/api/admin/users/$id/',
  path: '/api/admin/users/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsMeetingIdClassesIndexRoute =
  ApiMeetingsMeetingIdClassesIndexRouteImport.update({
    id: '/api/meetings/$meetingId/classes/',
    path: '/api/meetings/$meetingId/classes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdGeneralReportsIndexRoute =
  ApiMeetingsMeetingIdGeneralReportsIndexRouteImport.update({
    id: '/api/meetings/$meetingId/general-reports/',
    path: '/api/meetings/$meetingId/general-reports/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdGeneralReportsReportIdRoute =
  ApiMeetingsMeetingIdGeneralReportsReportIdRouteImport.update({
    id: '/api/meetings/$meetingId/general-reports/$reportId',
    path: '/api/meetings/$meetingId/general-reports/$reportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdMinutesIndexRoute =
  ApiMeetingsMeetingIdMinutesIndexRouteImport.update({
    id: '/api/meetings/$meetingId/minutes/',
    path: '/api/meetings/$meetingId/minutes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdMinutesApproveRoute =
  ApiMeetingsMeetingIdMinutesApproveRouteImport.update({
    id: '/api/meetings/$meetingId/minutes/approve',
    path: '/api/meetings/$meetingId/minutes/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdMinutesContentRoute =
  ApiMeetingsMeetingIdMinutesContentRouteImport.update({
    id: '/api/meetings/$meetingId/minutes/content',
    path: '/api/meetings/$meetingId/minutes/content',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdRecordsRecordIdRoute =
  ApiMeetingsMeetingIdRecordsRecordIdRouteImport.update({
    id: '/api/meetings/$meetingId/records/$recordId',
    path: '/api/meetings/$meetingId/records/$recordId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdClassesClassIdIndexRoute =
  ApiMeetingsMeetingIdClassesClassIdIndexRouteImport.update({
    id: '/api/meetings/$meetingId/classes/$classId/',
    path: '/api/meetings/$meetingId/classes/$classId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdClassesClassIdStudentsRoute =
  ApiMeetingsMeetingIdClassesClassIdStudentsRouteImport.update({
    id: '/api/meetings/$meetingId/classes/$classId/students',
    path: '/api/meetings/$meetingId/classes/$classId/students',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdMinutesVersionsIndexRoute =
  ApiMeetingsMeetingIdMinutesVersionsIndexRouteImport.update({
    id: '/api/meetings/$meetingId/minutes/versions/',
    path: '/api/meetings/$meetingId/minutes/versions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdStudentsStudentIdStatusRoute =
  ApiMeetingsMeetingIdStudentsStudentIdStatusRouteImport.update({
    id: '/api/meetings/$meetingId/students/$studentId/status',
    path: '/api/meetings/$meetingId/students/$studentId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute =
  ApiMeetingsMeetingIdMinutesVersionsVersionPdfRouteImport.update({
    id: '/api/meetings/$meetingId/minutes/versions/$version/pdf',
    path: '/api/meetings/$meetingId/minutes/versions/$version/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute =
  ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRouteImport.update({
    id: '/api/meetings/$meetingId/students/$studentId/records/',
    path: '/api/meetings/$meetingId/students/$studentId/records/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute =
  ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRouteImport.update(
    {
      id: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include',
      path: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/admin/users': typeof AppAdminUsersRoute
  '/classes/enroll': typeof AppClassesEnrollRoute
  '/components/$id': typeof AppComponentsIdRoute
  '/minutes/$meetingId': typeof AppMinutesMeetingIdRoute
  '/minutes/templates': typeof AppMinutesTemplatesRouteWithChildren
  '/roles/$id': typeof AppRolesIdRoute
  '/staff/$id': typeof AppStaffIdRoute
  '/students/$id': typeof AppStudentsIdRoute
  '/students/import': typeof AppStudentsImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invitations/status': typeof ApiInvitationsStatusRoute
  '/api/invitations/verify': typeof ApiInvitationsVerifyRoute
  '/api/students/import': typeof ApiStudentsImportRouteWithChildren
  '/classes/': typeof AppClassesIndexRoute
  '/components/': typeof AppComponentsIndexRoute
  '/meetings/': typeof AppMeetingsIndexRoute
  '/minutes/': typeof AppMinutesIndexRoute
  '/roles/': typeof AppRolesIndexRoute
  '/staff/': typeof AppStaffIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/api/classes/': typeof ApiClassesIndexRoute
  '/api/components/': typeof ApiComponentsIndexRoute
  '/api/enrollments/': typeof ApiEnrollmentsIndexRoute
  '/api/invitations/': typeof ApiInvitationsIndexRoute
  '/api/meetings/': typeof ApiMeetingsIndexRoute
  '/api/minute-templates/': typeof ApiMinuteTemplatesIndexRoute
  '/api/minutes/': typeof ApiMinutesIndexRoute
  '/api/roles/': typeof ApiRolesIndexRoute
  '/api/staff/': typeof ApiStaffIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/classes/$id/offers': typeof AppClassesIdOffersRoute
  '/classes/$id/students': typeof AppClassesIdStudentsRoute
  '/meetings/$meetingId/council': typeof AppMeetingsMeetingIdCouncilRoute
  '/meetings/$meetingId/participants': typeof AppMeetingsMeetingIdParticipantsRoute
  '/meetings/$meetingId/students': typeof AppMeetingsMeetingIdStudentsRoute
  '/minutes/templates/$id': typeof AppMinutesTemplatesIdRoute
  '/api/classes/$id/history': typeof ApiClassesIdHistoryRoute
  '/api/classes/$id/offers': typeof ApiClassesIdOffersRoute
  '/api/classes/$id/students': typeof ApiClassesIdStudentsRoute
  '/api/meetings/$meetingId/participants': typeof ApiMeetingsMeetingIdParticipantsRoute
  '/api/meetings/$meetingId/reopen': typeof ApiMeetingsMeetingIdReopenRoute
  '/api/students/$id/history': typeof ApiStudentsIdHistoryRoute
  '/api/students/$id/records': typeof ApiStudentsIdRecordsRoute
  '/api/students/import/resolve': typeof ApiStudentsImportResolveRoute
  '/meetings/$meetingId/': typeof AppMeetingsMeetingIdIndexRoute
  '/minutes/templates/': typeof AppMinutesTemplatesIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/classes/$id/': typeof ApiClassesIdIndexRoute
  '/api/components/$id/': typeof ApiComponentsIdIndexRoute
  '/api/invitations/$id/': typeof ApiInvitationsIdIndexRoute
  '/api/meetings/$meetingId/': typeof ApiMeetingsMeetingIdIndexRoute
  '/api/minute-templates/$id/': typeof ApiMinuteTemplatesIdIndexRoute
  '/api/roles/$id/': typeof ApiRolesIdIndexRoute
  '/api/staff/$id/': typeof ApiStaffIdIndexRoute
  '/api/students/$id/': typeof ApiStudentsIdIndexRoute
  '/api/meetings/$meetingId/general-reports/$reportId': typeof ApiMeetingsMeetingIdGeneralReportsReportIdRoute
  '/api/meetings/$meetingId/minutes/approve': typeof ApiMeetingsMeetingIdMinutesApproveRoute
  '/api/meetings/$meetingId/minutes/content': typeof ApiMeetingsMeetingIdMinutesContentRoute
  '/api/meetings/$meetingId/records/$recordId': typeof ApiMeetingsMeetingIdRecordsRecordIdRoute
  '/api/admin/users/$id/': typeof ApiAdminUsersIdIndexRoute
  '/api/meetings/$meetingId/classes/': typeof ApiMeetingsMeetingIdClassesIndexRoute
  '/api/meetings/$meetingId/general-reports/': typeof ApiMeetingsMeetingIdGeneralReportsIndexRoute
  '/api/meetings/$meetingId/minutes/': typeof ApiMeetingsMeetingIdMinutesIndexRoute
  '/api/meetings/$meetingId/classes/$classId/students': typeof ApiMeetingsMeetingIdClassesClassIdStudentsRoute
  '/api/meetings/$meetingId/students/$studentId/status': typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRoute
  '/api/meetings/$meetingId/classes/$classId/': typeof ApiMeetingsMeetingIdClassesClassIdIndexRoute
  '/api/meetings/$meetingId/minutes/versions/': typeof ApiMeetingsMeetingIdMinutesVersionsIndexRoute
  '/api/meetings/$meetingId/minutes/versions/$version/pdf': typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute
  '/api/meetings/$meetingId/students/$studentId/records/': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute
  '/api/meetings/$meetingId/students/$studentId/records/$recordId/include': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/classes/enroll': typeof AppClassesEnrollRoute
  '/components/$id': typeof AppComponentsIdRoute
  '/minutes/$meetingId': typeof AppMinutesMeetingIdRoute
  '/roles/$id': typeof AppRolesIdRoute
  '/staff/$id': typeof AppStaffIdRoute
  '/students/$id': typeof AppStudentsIdRoute
  '/students/import': typeof AppStudentsImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invitations/status': typeof ApiInvitationsStatusRoute
  '/api/invitations/verify': typeof ApiInvitationsVerifyRoute
  '/api/students/import': typeof ApiStudentsImportRouteWithChildren
  '/classes': typeof AppClassesIndexRoute
  '/components': typeof AppComponentsIndexRoute
  '/meetings': typeof AppMeetingsIndexRoute
  '/minutes': typeof AppMinutesIndexRoute
  '/roles': typeof AppRolesIndexRoute
  '/staff': typeof AppStaffIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/api/classes': typeof ApiClassesIndexRoute
  '/api/components': typeof ApiComponentsIndexRoute
  '/api/enrollments': typeof ApiEnrollmentsIndexRoute
  '/api/invitations': typeof ApiInvitationsIndexRoute
  '/api/meetings': typeof ApiMeetingsIndexRoute
  '/api/minute-templates': typeof ApiMinuteTemplatesIndexRoute
  '/api/minutes': typeof ApiMinutesIndexRoute
  '/api/roles': typeof ApiRolesIndexRoute
  '/api/staff': typeof ApiStaffIndexRoute
  '/api/students': typeof ApiStudentsIndexRoute
  '/classes/$id/offers': typeof AppClassesIdOffersRoute
  '/classes/$id/students': typeof AppClassesIdStudentsRoute
  '/meetings/$meetingId/council': typeof AppMeetingsMeetingIdCouncilRoute
  '/meetings/$meetingId/participants': typeof AppMeetingsMeetingIdParticipantsRoute
  '/meetings/$meetingId/students': typeof AppMeetingsMeetingIdStudentsRoute
  '/minutes/templates/$id': typeof AppMinutesTemplatesIdRoute
  '/api/classes/$id/history': typeof ApiClassesIdHistoryRoute
  '/api/classes/$id/offers': typeof ApiClassesIdOffersRoute
  '/api/classes/$id/students': typeof ApiClassesIdStudentsRoute
  '/api/meetings/$meetingId/participants': typeof ApiMeetingsMeetingIdParticipantsRoute
  '/api/meetings/$meetingId/reopen': typeof ApiMeetingsMeetingIdReopenRoute
  '/api/students/$id/history': typeof ApiStudentsIdHistoryRoute
  '/api/students/$id/records': typeof ApiStudentsIdRecordsRoute
  '/api/students/import/resolve': typeof ApiStudentsImportResolveRoute
  '/meetings/$meetingId': typeof AppMeetingsMeetingIdIndexRoute
  '/minutes/templates': typeof AppMinutesTemplatesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersIndexRoute
  '/api/classes/$id': typeof ApiClassesIdIndexRoute
  '/api/components/$id': typeof ApiComponentsIdIndexRoute
  '/api/invitations/$id': typeof ApiInvitationsIdIndexRoute
  '/api/meetings/$meetingId': typeof ApiMeetingsMeetingIdIndexRoute
  '/api/minute-templates/$id': typeof ApiMinuteTemplatesIdIndexRoute
  '/api/roles/$id': typeof ApiRolesIdIndexRoute
  '/api/staff/$id': typeof ApiStaffIdIndexRoute
  '/api/students/$id': typeof ApiStudentsIdIndexRoute
  '/api/meetings/$meetingId/general-reports/$reportId': typeof ApiMeetingsMeetingIdGeneralReportsReportIdRoute
  '/api/meetings/$meetingId/minutes/approve': typeof ApiMeetingsMeetingIdMinutesApproveRoute
  '/api/meetings/$meetingId/minutes/content': typeof ApiMeetingsMeetingIdMinutesContentRoute
  '/api/meetings/$meetingId/records/$recordId': typeof ApiMeetingsMeetingIdRecordsRecordIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdIndexRoute
  '/api/meetings/$meetingId/classes': typeof ApiMeetingsMeetingIdClassesIndexRoute
  '/api/meetings/$meetingId/general-reports': typeof ApiMeetingsMeetingIdGeneralReportsIndexRoute
  '/api/meetings/$meetingId/minutes': typeof ApiMeetingsMeetingIdMinutesIndexRoute
  '/api/meetings/$meetingId/classes/$classId/students': typeof ApiMeetingsMeetingIdClassesClassIdStudentsRoute
  '/api/meetings/$meetingId/students/$studentId/status': typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRoute
  '/api/meetings/$meetingId/classes/$classId': typeof ApiMeetingsMeetingIdClassesClassIdIndexRoute
  '/api/meetings/$meetingId/minutes/versions': typeof ApiMeetingsMeetingIdMinutesVersionsIndexRoute
  '/api/meetings/$meetingId/minutes/versions/$version/pdf': typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute
  '/api/meetings/$meetingId/students/$studentId/records': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute
  '/api/meetings/$meetingId/students/$studentId/records/$recordId/include': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/classes/enroll': typeof AppClassesEnrollRoute
  '/_app/components/$id': typeof AppComponentsIdRoute
  '/_app/minutes/$meetingId': typeof AppMinutesMeetingIdRoute
  '/_app/minutes/templates': typeof AppMinutesTemplatesRouteWithChildren
  '/_app/roles/$id': typeof AppRolesIdRoute
  '/_app/staff/$id': typeof AppStaffIdRoute
  '/_app/students/$id': typeof AppStudentsIdRoute
  '/_app/students/import': typeof AppStudentsImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invitations/status': typeof ApiInvitationsStatusRoute
  '/api/invitations/verify': typeof ApiInvitationsVerifyRoute
  '/api/students/import': typeof ApiStudentsImportRouteWithChildren
  '/_app/classes/': typeof AppClassesIndexRoute
  '/_app/components/': typeof AppComponentsIndexRoute
  '/_app/meetings/': typeof AppMeetingsIndexRoute
  '/_app/minutes/': typeof AppMinutesIndexRoute
  '/_app/roles/': typeof AppRolesIndexRoute
  '/_app/staff/': typeof AppStaffIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/api/classes/': typeof ApiClassesIndexRoute
  '/api/components/': typeof ApiComponentsIndexRoute
  '/api/enrollments/': typeof ApiEnrollmentsIndexRoute
  '/api/invitations/': typeof ApiInvitationsIndexRoute
  '/api/meetings/': typeof ApiMeetingsIndexRoute
  '/api/minute-templates/': typeof ApiMinuteTemplatesIndexRoute
  '/api/minutes/': typeof ApiMinutesIndexRoute
  '/api/roles/': typeof ApiRolesIndexRoute
  '/api/staff/': typeof ApiStaffIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/_app/classes/$id/offers': typeof AppClassesIdOffersRoute
  '/_app/classes/$id/students': typeof AppClassesIdStudentsRoute
  '/_app/meetings/$meetingId/council': typeof AppMeetingsMeetingIdCouncilRoute
  '/_app/meetings/$meetingId/participants': typeof AppMeetingsMeetingIdParticipantsRoute
  '/_app/meetings/$meetingId/students': typeof AppMeetingsMeetingIdStudentsRoute
  '/_app/minutes/templates/$id': typeof AppMinutesTemplatesIdRoute
  '/api/classes/$id/history': typeof ApiClassesIdHistoryRoute
  '/api/classes/$id/offers': typeof ApiClassesIdOffersRoute
  '/api/classes/$id/students': typeof ApiClassesIdStudentsRoute
  '/api/meetings/$meetingId/participants': typeof ApiMeetingsMeetingIdParticipantsRoute
  '/api/meetings/$meetingId/reopen': typeof ApiMeetingsMeetingIdReopenRoute
  '/api/students/$id/history': typeof ApiStudentsIdHistoryRoute
  '/api/students/$id/records': typeof ApiStudentsIdRecordsRoute
  '/api/students/import/resolve': typeof ApiStudentsImportResolveRoute
  '/_app/meetings/$meetingId/': typeof AppMeetingsMeetingIdIndexRoute
  '/_app/minutes/templates/': typeof AppMinutesTemplatesIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/classes/$id/': typeof ApiClassesIdIndexRoute
  '/api/components/$id/': typeof ApiComponentsIdIndexRoute
  '/api/invitations/$id/': typeof ApiInvitationsIdIndexRoute
  '/api/meetings/$meetingId/': typeof ApiMeetingsMeetingIdIndexRoute
  '/api/minute-templates/$id/': typeof ApiMinuteTemplatesIdIndexRoute
  '/api/roles/$id/': typeof ApiRolesIdIndexRoute
  '/api/staff/$id/': typeof ApiStaffIdIndexRoute
  '/api/students/$id/': typeof ApiStudentsIdIndexRoute
  '/api/meetings/$meetingId/general-reports/$reportId': typeof ApiMeetingsMeetingIdGeneralReportsReportIdRoute
  '/api/meetings/$meetingId/minutes/approve': typeof ApiMeetingsMeetingIdMinutesApproveRoute
  '/api/meetings/$meetingId/minutes/content': typeof ApiMeetingsMeetingIdMinutesContentRoute
  '/api/meetings/$meetingId/records/$recordId': typeof ApiMeetingsMeetingIdRecordsRecordIdRoute
  '/api/admin/users/$id/': typeof ApiAdminUsersIdIndexRoute
  '/api/meetings/$meetingId/classes/': typeof ApiMeetingsMeetingIdClassesIndexRoute
  '/api/meetings/$meetingId/general-reports/': typeof ApiMeetingsMeetingIdGeneralReportsIndexRoute
  '/api/meetings/$meetingId/minutes/': typeof ApiMeetingsMeetingIdMinutesIndexRoute
  '/api/meetings/$meetingId/classes/$classId/students': typeof ApiMeetingsMeetingIdClassesClassIdStudentsRoute
  '/api/meetings/$meetingId/students/$studentId/status': typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRoute
  '/api/meetings/$meetingId/classes/$classId/': typeof ApiMeetingsMeetingIdClassesClassIdIndexRoute
  '/api/meetings/$meetingId/minutes/versions/': typeof ApiMeetingsMeetingIdMinutesVersionsIndexRoute
  '/api/meetings/$meetingId/minutes/versions/$version/pdf': typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute
  '/api/meetings/$meetingId/students/$studentId/records/': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute
  '/api/meetings/$meetingId/students/$studentId/records/$recordId/include': typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/admin/users'
    | '/classes/enroll'
    | '/components/$id'
    | '/minutes/$meetingId'
    | '/minutes/templates'
    | '/roles/$id'
    | '/staff/$id'
    | '/students/$id'
    | '/students/import'
    | '/api/auth/$'
    | '/api/invitations/status'
    | '/api/invitations/verify'
    | '/api/students/import'
    | '/classes/'
    | '/components/'
    | '/meetings/'
    | '/minutes/'
    | '/roles/'
    | '/staff/'
    | '/students/'
    | '/api/classes/'
    | '/api/components/'
    | '/api/enrollments/'
    | '/api/invitations/'
    | '/api/meetings/'
    | '/api/minute-templates/'
    | '/api/minutes/'
    | '/api/roles/'
    | '/api/staff/'
    | '/api/students/'
    | '/classes/$id/offers'
    | '/classes/$id/students'
    | '/meetings/$meetingId/council'
    | '/meetings/$meetingId/participants'
    | '/meetings/$meetingId/students'
    | '/minutes/templates/$id'
    | '/api/classes/$id/history'
    | '/api/classes/$id/offers'
    | '/api/classes/$id/students'
    | '/api/meetings/$meetingId/participants'
    | '/api/meetings/$meetingId/reopen'
    | '/api/students/$id/history'
    | '/api/students/$id/records'
    | '/api/students/import/resolve'
    | '/meetings/$meetingId/'
    | '/minutes/templates/'
    | '/api/admin/users/'
    | '/api/classes/$id/'
    | '/api/components/$id/'
    | '/api/invitations/$id/'
    | '/api/meetings/$meetingId/'
    | '/api/minute-templates/$id/'
    | '/api/roles/$id/'
    | '/api/staff/$id/'
    | '/api/students/$id/'
    | '/api/meetings/$meetingId/general-reports/$reportId'
    | '/api/meetings/$meetingId/minutes/approve'
    | '/api/meetings/$meetingId/minutes/content'
    | '/api/meetings/$meetingId/records/$recordId'
    | '/api/admin/users/$id/'
    | '/api/meetings/$meetingId/classes/'
    | '/api/meetings/$meetingId/general-reports/'
    | '/api/meetings/$meetingId/minutes/'
    | '/api/meetings/$meetingId/classes/$classId/students'
    | '/api/meetings/$meetingId/students/$studentId/status'
    | '/api/meetings/$meetingId/classes/$classId/'
    | '/api/meetings/$meetingId/minutes/versions/'
    | '/api/meetings/$meetingId/minutes/versions/$version/pdf'
    | '/api/meetings/$meetingId/students/$studentId/records/'
    | '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/admin'
    | '/'
    | '/admin/users'
    | '/classes/enroll'
    | '/components/$id'
    | '/minutes/$meetingId'
    | '/roles/$id'
    | '/staff/$id'
    | '/students/$id'
    | '/students/import'
    | '/api/auth/$'
    | '/api/invitations/status'
    | '/api/invitations/verify'
    | '/api/students/import'
    | '/classes'
    | '/components'
    | '/meetings'
    | '/minutes'
    | '/roles'
    | '/staff'
    | '/students'
    | '/api/classes'
    | '/api/components'
    | '/api/enrollments'
    | '/api/invitations'
    | '/api/meetings'
    | '/api/minute-templates'
    | '/api/minutes'
    | '/api/roles'
    | '/api/staff'
    | '/api/students'
    | '/classes/$id/offers'
    | '/classes/$id/students'
    | '/meetings/$meetingId/council'
    | '/meetings/$meetingId/participants'
    | '/meetings/$meetingId/students'
    | '/minutes/templates/$id'
    | '/api/classes/$id/history'
    | '/api/classes/$id/offers'
    | '/api/classes/$id/students'
    | '/api/meetings/$meetingId/participants'
    | '/api/meetings/$meetingId/reopen'
    | '/api/students/$id/history'
    | '/api/students/$id/records'
    | '/api/students/import/resolve'
    | '/meetings/$meetingId'
    | '/minutes/templates'
    | '/api/admin/users'
    | '/api/classes/$id'
    | '/api/components/$id'
    | '/api/invitations/$id'
    | '/api/meetings/$meetingId'
    | '/api/minute-templates/$id'
    | '/api/roles/$id'
    | '/api/staff/$id'
    | '/api/students/$id'
    | '/api/meetings/$meetingId/general-reports/$reportId'
    | '/api/meetings/$meetingId/minutes/approve'
    | '/api/meetings/$meetingId/minutes/content'
    | '/api/meetings/$meetingId/records/$recordId'
    | '/api/admin/users/$id'
    | '/api/meetings/$meetingId/classes'
    | '/api/meetings/$meetingId/general-reports'
    | '/api/meetings/$meetingId/minutes'
    | '/api/meetings/$meetingId/classes/$classId/students'
    | '/api/meetings/$meetingId/students/$studentId/status'
    | '/api/meetings/$meetingId/classes/$classId'
    | '/api/meetings/$meetingId/minutes/versions'
    | '/api/meetings/$meetingId/minutes/versions/$version/pdf'
    | '/api/meetings/$meetingId/students/$studentId/records'
    | '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/'
    | '/_app/admin/users'
    | '/_app/classes/enroll'
    | '/_app/components/$id'
    | '/_app/minutes/$meetingId'
    | '/_app/minutes/templates'
    | '/_app/roles/$id'
    | '/_app/staff/$id'
    | '/_app/students/$id'
    | '/_app/students/import'
    | '/api/auth/$'
    | '/api/invitations/status'
    | '/api/invitations/verify'
    | '/api/students/import'
    | '/_app/classes/'
    | '/_app/components/'
    | '/_app/meetings/'
    | '/_app/minutes/'
    | '/_app/roles/'
    | '/_app/staff/'
    | '/_app/students/'
    | '/api/classes/'
    | '/api/components/'
    | '/api/enrollments/'
    | '/api/invitations/'
    | '/api/meetings/'
    | '/api/minute-templates/'
    | '/api/minutes/'
    | '/api/roles/'
    | '/api/staff/'
    | '/api/students/'
    | '/_app/classes/$id/offers'
    | '/_app/classes/$id/students'
    | '/_app/meetings/$meetingId/council'
    | '/_app/meetings/$meetingId/participants'
    | '/_app/meetings/$meetingId/students'
    | '/_app/minutes/templates/$id'
    | '/api/classes/$id/history'
    | '/api/classes/$id/offers'
    | '/api/classes/$id/students'
    | '/api/meetings/$meetingId/participants'
    | '/api/meetings/$meetingId/reopen'
    | '/api/students/$id/history'
    | '/api/students/$id/records'
    | '/api/students/import/resolve'
    | '/_app/meetings/$meetingId/'
    | '/_app/minutes/templates/'
    | '/api/admin/users/'
    | '/api/classes/$id/'
    | '/api/components/$id/'
    | '/api/invitations/$id/'
    | '/api/meetings/$meetingId/'
    | '/api/minute-templates/$id/'
    | '/api/roles/$id/'
    | '/api/staff/$id/'
    | '/api/students/$id/'
    | '/api/meetings/$meetingId/general-reports/$reportId'
    | '/api/meetings/$meetingId/minutes/approve'
    | '/api/meetings/$meetingId/minutes/content'
    | '/api/meetings/$meetingId/records/$recordId'
    | '/api/admin/users/$id/'
    | '/api/meetings/$meetingId/classes/'
    | '/api/meetings/$meetingId/general-reports/'
    | '/api/meetings/$meetingId/minutes/'
    | '/api/meetings/$meetingId/classes/$classId/students'
    | '/api/meetings/$meetingId/students/$studentId/status'
    | '/api/meetings/$meetingId/classes/$classId/'
    | '/api/meetings/$meetingId/minutes/versions/'
    | '/api/meetings/$meetingId/minutes/versions/$version/pdf'
    | '/api/meetings/$meetingId/students/$studentId/records/'
    | '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInvitationsStatusRoute: typeof ApiInvitationsStatusRoute
  ApiInvitationsVerifyRoute: typeof ApiInvitationsVerifyRoute
  ApiStudentsImportRoute: typeof ApiStudentsImportRouteWithChildren
  ApiClassesIndexRoute: typeof ApiClassesIndexRoute
  ApiComponentsIndexRoute: typeof ApiComponentsIndexRoute
  ApiEnrollmentsIndexRoute: typeof ApiEnrollmentsIndexRoute
  ApiInvitationsIndexRoute: typeof ApiInvitationsIndexRoute
  ApiMeetingsIndexRoute: typeof ApiMeetingsIndexRoute
  ApiMinuteTemplatesIndexRoute: typeof ApiMinuteTemplatesIndexRoute
  ApiMinutesIndexRoute: typeof ApiMinutesIndexRoute
  ApiRolesIndexRoute: typeof ApiRolesIndexRoute
  ApiStaffIndexRoute: typeof ApiStaffIndexRoute
  ApiStudentsIndexRoute: typeof ApiStudentsIndexRoute
  ApiClassesIdHistoryRoute: typeof ApiClassesIdHistoryRoute
  ApiClassesIdOffersRoute: typeof ApiClassesIdOffersRoute
  ApiClassesIdStudentsRoute: typeof ApiClassesIdStudentsRoute
  ApiMeetingsMeetingIdParticipantsRoute: typeof ApiMeetingsMeetingIdParticipantsRoute
  ApiMeetingsMeetingIdReopenRoute: typeof ApiMeetingsMeetingIdReopenRoute
  ApiStudentsIdHistoryRoute: typeof ApiStudentsIdHistoryRoute
  ApiStudentsIdRecordsRoute: typeof ApiStudentsIdRecordsRoute
  ApiAdminUsersIndexRoute: typeof ApiAdminUsersIndexRoute
  ApiClassesIdIndexRoute: typeof ApiClassesIdIndexRoute
  ApiComponentsIdIndexRoute: typeof ApiComponentsIdIndexRoute
  ApiInvitationsIdIndexRoute: typeof ApiInvitationsIdIndexRoute
  ApiMeetingsMeetingIdIndexRoute: typeof ApiMeetingsMeetingIdIndexRoute
  ApiMinuteTemplatesIdIndexRoute: typeof ApiMinuteTemplatesIdIndexRoute
  ApiRolesIdIndexRoute: typeof ApiRolesIdIndexRoute
  ApiStaffIdIndexRoute: typeof ApiStaffIdIndexRoute
  ApiStudentsIdIndexRoute: typeof ApiStudentsIdIndexRoute
  ApiMeetingsMeetingIdGeneralReportsReportIdRoute: typeof ApiMeetingsMeetingIdGeneralReportsReportIdRoute
  ApiMeetingsMeetingIdMinutesApproveRoute: typeof ApiMeetingsMeetingIdMinutesApproveRoute
  ApiMeetingsMeetingIdMinutesContentRoute: typeof ApiMeetingsMeetingIdMinutesContentRoute
  ApiMeetingsMeetingIdRecordsRecordIdRoute: typeof ApiMeetingsMeetingIdRecordsRecordIdRoute
  ApiAdminUsersIdIndexRoute: typeof ApiAdminUsersIdIndexRoute
  ApiMeetingsMeetingIdClassesIndexRoute: typeof ApiMeetingsMeetingIdClassesIndexRoute
  ApiMeetingsMeetingIdGeneralReportsIndexRoute: typeof ApiMeetingsMeetingIdGeneralReportsIndexRoute
  ApiMeetingsMeetingIdMinutesIndexRoute: typeof ApiMeetingsMeetingIdMinutesIndexRoute
  ApiMeetingsMeetingIdClassesClassIdStudentsRoute: typeof ApiMeetingsMeetingIdClassesClassIdStudentsRoute
  ApiMeetingsMeetingIdStudentsStudentIdStatusRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRoute
  ApiMeetingsMeetingIdClassesClassIdIndexRoute: typeof ApiMeetingsMeetingIdClassesClassIdIndexRoute
  ApiMeetingsMeetingIdMinutesVersionsIndexRoute: typeof ApiMeetingsMeetingIdMinutesVersionsIndexRoute
  ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute: typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute
  ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute
  ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/classes/': {
      id: '/_app/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AppClassesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/classes/enroll': {
      id: '/_app/classes/enroll'
      path: '/classes/enroll'
      fullPath: '/classes/enroll'
      preLoaderRoute: typeof AppClassesEnrollRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/components/': {
      id: '/_app/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof AppComponentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/components/$id': {
      id: '/_app/components/$id'
      path: '/components/$id'
      fullPath: '/components/$id'
      preLoaderRoute: typeof AppComponentsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/': {
      id: '/_app/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AppMeetingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/minutes/': {
      id: '/_app/minutes/'
      path: '/minutes'
      fullPath: '/minutes/'
      preLoaderRoute: typeof AppMinutesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/minutes/$meetingId': {
      id: '/_app/minutes/$meetingId'
      path: '/minutes/$meetingId'
      fullPath: '/minutes/$meetingId'
      preLoaderRoute: typeof AppMinutesMeetingIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/minutes/templates': {
      id: '/_app/minutes/templates'
      path: '/minutes/templates'
      fullPath: '/minutes/templates'
      preLoaderRoute: typeof AppMinutesTemplatesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles/$id': {
      id: '/_app/roles/$id'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AppRolesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/staff/$id': {
      id: '/_app/staff/$id'
      path: '/staff/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AppStaffIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students/$id': {
      id: '/_app/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/students/import': {
      id: '/_app/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AppStudentsImportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/': {
      id: '/api/classes/'
      path: '/api/classes'
      fullPath: '/api/classes/'
      preLoaderRoute: typeof ApiClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/components/': {
      id: '/api/components/'
      path: '/api/components'
      fullPath: '/api/components/'
      preLoaderRoute: typeof ApiComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrollments/': {
      id: '/api/enrollments/'
      path: '/api/enrollments'
      fullPath: '/api/enrollments/'
      preLoaderRoute: typeof ApiEnrollmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations/': {
      id: '/api/invitations/'
      path: '/api/invitations'
      fullPath: '/api/invitations/'
      preLoaderRoute: typeof ApiInvitationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations/status': {
      id: '/api/invitations/status'
      path: '/api/invitations/status'
      fullPath: '/api/invitations/status'
      preLoaderRoute: typeof ApiInvitationsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations/verify': {
      id: '/api/invitations/verify'
      path: '/api/invitations/verify'
      fullPath: '/api/invitations/verify'
      preLoaderRoute: typeof ApiInvitationsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/': {
      id: '/api/meetings/'
      path: '/api/meetings'
      fullPath: '/api/meetings/'
      preLoaderRoute: typeof ApiMeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/minute-templates/': {
      id: '/api/minute-templates/'
      path: '/api/minute-templates'
      fullPath: '/api/minute-templates/'
      preLoaderRoute: typeof ApiMinuteTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/minutes/': {
      id: '/api/minutes/'
      path: '/api/minutes'
      fullPath: '/api/minutes/'
      preLoaderRoute: typeof ApiMinutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roles/': {
      id: '/api/roles/'
      path: '/api/roles'
      fullPath: '/api/roles/'
      preLoaderRoute: typeof ApiRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/': {
      id: '/api/staff/'
      path: '/api/staff'
      fullPath: '/api/staff/'
      preLoaderRoute: typeof ApiStaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/': {
      id: '/api/students/'
      path: '/api/students'
      fullPath: '/api/students/'
      preLoaderRoute: typeof ApiStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/import': {
      id: '/api/students/import'
      path: '/api/students/import'
      fullPath: '/api/students/import'
      preLoaderRoute: typeof ApiStudentsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/classes/$id/offers': {
      id: '/_app/classes/$id/offers'
      path: '/classes/$id/offers'
      fullPath: '/classes/$id/offers'
      preLoaderRoute: typeof AppClassesIdOffersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/classes/$id/students': {
      id: '/_app/classes/$id/students'
      path: '/classes/$id/students'
      fullPath: '/classes/$id/students'
      preLoaderRoute: typeof AppClassesIdStudentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/$meetingId/': {
      id: '/_app/meetings/$meetingId/'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId/'
      preLoaderRoute: typeof AppMeetingsMeetingIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/$meetingId/council': {
      id: '/_app/meetings/$meetingId/council'
      path: '/meetings/$meetingId/council'
      fullPath: '/meetings/$meetingId/council'
      preLoaderRoute: typeof AppMeetingsMeetingIdCouncilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/$meetingId/participants': {
      id: '/_app/meetings/$meetingId/participants'
      path: '/meetings/$meetingId/participants'
      fullPath: '/meetings/$meetingId/participants'
      preLoaderRoute: typeof AppMeetingsMeetingIdParticipantsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/meetings/$meetingId/students': {
      id: '/_app/meetings/$meetingId/students'
      path: '/meetings/$meetingId/students'
      fullPath: '/meetings/$meetingId/students'
      preLoaderRoute: typeof AppMeetingsMeetingIdStudentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/minutes/templates/': {
      id: '/_app/minutes/templates/'
      path: '/'
      fullPath: '/minutes/templates/'
      preLoaderRoute: typeof AppMinutesTemplatesIndexRouteImport
      parentRoute: typeof AppMinutesTemplatesRoute
    }
    '/_app/minutes/templates/$id': {
      id: '/_app/minutes/templates/$id'
      path: '/$id'
      fullPath: '/minutes/templates/$id'
      preLoaderRoute: typeof AppMinutesTemplatesIdRouteImport
      parentRoute: typeof AppMinutesTemplatesRoute
    }
    '/api/admin/users/': {
      id: '/api/admin/users/'
      path: '/api/admin/users'
      fullPath: '/api/admin/users/'
      preLoaderRoute: typeof ApiAdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/$id/': {
      id: '/api/classes/$id/'
      path: '/api/classes/$id'
      fullPath: '/api/classes/$id/'
      preLoaderRoute: typeof ApiClassesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/$id/history': {
      id: '/api/classes/$id/history'
      path: '/api/classes/$id/history'
      fullPath: '/api/classes/$id/history'
      preLoaderRoute: typeof ApiClassesIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/$id/offers': {
      id: '/api/classes/$id/offers'
      path: '/api/classes/$id/offers'
      fullPath: '/api/classes/$id/offers'
      preLoaderRoute: typeof ApiClassesIdOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/$id/students': {
      id: '/api/classes/$id/students'
      path: '/api/classes/$id/students'
      fullPath: '/api/classes/$id/students'
      preLoaderRoute: typeof ApiClassesIdStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/components/$id/': {
      id: '/api/components/$id/'
      path: '/api/components/$id'
      fullPath: '/api/components/$id/'
      preLoaderRoute: typeof ApiComponentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations/$id/': {
      id: '/api/invitations/$id/'
      path: '/api/invitations/$id'
      fullPath: '/api/invitations/$id/'
      preLoaderRoute: typeof ApiInvitationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/': {
      id: '/api/meetings/$meetingId/'
      path: '/api/meetings/$meetingId'
      fullPath: '/api/meetings/$meetingId/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/participants': {
      id: '/api/meetings/$meetingId/participants'
      path: '/api/meetings/$meetingId/participants'
      fullPath: '/api/meetings/$meetingId/participants'
      preLoaderRoute: typeof ApiMeetingsMeetingIdParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/reopen': {
      id: '/api/meetings/$meetingId/reopen'
      path: '/api/meetings/$meetingId/reopen'
      fullPath: '/api/meetings/$meetingId/reopen'
      preLoaderRoute: typeof ApiMeetingsMeetingIdReopenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/minute-templates/$id/': {
      id: '/api/minute-templates/$id/'
      path: '/api/minute-templates/$id'
      fullPath: '/api/minute-templates/$id/'
      preLoaderRoute: typeof ApiMinuteTemplatesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roles/$id/': {
      id: '/api/roles/$id/'
      path: '/api/roles/$id'
      fullPath: '/api/roles/$id/'
      preLoaderRoute: typeof ApiRolesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/$id/': {
      id: '/api/staff/$id/'
      path: '/api/staff/$id'
      fullPath: '/api/staff/$id/'
      preLoaderRoute: typeof ApiStaffIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/$id/': {
      id: '/api/students/$id/'
      path: '/api/students/$id'
      fullPath: '/api/students/$id/'
      preLoaderRoute: typeof ApiStudentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/$id/history': {
      id: '/api/students/$id/history'
      path: '/api/students/$id/history'
      fullPath: '/api/students/$id/history'
      preLoaderRoute: typeof ApiStudentsIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/$id/records': {
      id: '/api/students/$id/records'
      path: '/api/students/$id/records'
      fullPath: '/api/students/$id/records'
      preLoaderRoute: typeof ApiStudentsIdRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/import/resolve': {
      id: '/api/students/import/resolve'
      path: '/resolve'
      fullPath: '/api/students/import/resolve'
      preLoaderRoute: typeof ApiStudentsImportResolveRouteImport
      parentRoute: typeof ApiStudentsImportRoute
    }
    '/api/admin/users/$id/': {
      id: '/api/admin/users/$id/'
      path: '/api/admin/users/$id'
      fullPath: '/api/admin/users/$id/'
      preLoaderRoute: typeof ApiAdminUsersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/classes/': {
      id: '/api/meetings/$meetingId/classes/'
      path: '/api/meetings/$meetingId/classes'
      fullPath: '/api/meetings/$meetingId/classes/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/general-reports/': {
      id: '/api/meetings/$meetingId/general-reports/'
      path: '/api/meetings/$meetingId/general-reports'
      fullPath: '/api/meetings/$meetingId/general-reports/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdGeneralReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/general-reports/$reportId': {
      id: '/api/meetings/$meetingId/general-reports/$reportId'
      path: '/api/meetings/$meetingId/general-reports/$reportId'
      fullPath: '/api/meetings/$meetingId/general-reports/$reportId'
      preLoaderRoute: typeof ApiMeetingsMeetingIdGeneralReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/minutes/': {
      id: '/api/meetings/$meetingId/minutes/'
      path: '/api/meetings/$meetingId/minutes'
      fullPath: '/api/meetings/$meetingId/minutes/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdMinutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/minutes/approve': {
      id: '/api/meetings/$meetingId/minutes/approve'
      path: '/api/meetings/$meetingId/minutes/approve'
      fullPath: '/api/meetings/$meetingId/minutes/approve'
      preLoaderRoute: typeof ApiMeetingsMeetingIdMinutesApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/minutes/content': {
      id: '/api/meetings/$meetingId/minutes/content'
      path: '/api/meetings/$meetingId/minutes/content'
      fullPath: '/api/meetings/$meetingId/minutes/content'
      preLoaderRoute: typeof ApiMeetingsMeetingIdMinutesContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/records/$recordId': {
      id: '/api/meetings/$meetingId/records/$recordId'
      path: '/api/meetings/$meetingId/records/$recordId'
      fullPath: '/api/meetings/$meetingId/records/$recordId'
      preLoaderRoute: typeof ApiMeetingsMeetingIdRecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/classes/$classId/': {
      id: '/api/meetings/$meetingId/classes/$classId/'
      path: '/api/meetings/$meetingId/classes/$classId'
      fullPath: '/api/meetings/$meetingId/classes/$classId/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdClassesClassIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/classes/$classId/students': {
      id: '/api/meetings/$meetingId/classes/$classId/students'
      path: '/api/meetings/$meetingId/classes/$classId/students'
      fullPath: '/api/meetings/$meetingId/classes/$classId/students'
      preLoaderRoute: typeof ApiMeetingsMeetingIdClassesClassIdStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/minutes/versions/': {
      id: '/api/meetings/$meetingId/minutes/versions/'
      path: '/api/meetings/$meetingId/minutes/versions'
      fullPath: '/api/meetings/$meetingId/minutes/versions/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdMinutesVersionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/students/$studentId/status': {
      id: '/api/meetings/$meetingId/students/$studentId/status'
      path: '/api/meetings/$meetingId/students/$studentId/status'
      fullPath: '/api/meetings/$meetingId/students/$studentId/status'
      preLoaderRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/minutes/versions/$version/pdf': {
      id: '/api/meetings/$meetingId/minutes/versions/$version/pdf'
      path: '/api/meetings/$meetingId/minutes/versions/$version/pdf'
      fullPath: '/api/meetings/$meetingId/minutes/versions/$version/pdf'
      preLoaderRoute: typeof ApiMeetingsMeetingIdMinutesVersionsVersionPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/students/$studentId/records/': {
      id: '/api/meetings/$meetingId/students/$studentId/records/'
      path: '/api/meetings/$meetingId/students/$studentId/records'
      fullPath: '/api/meetings/$meetingId/students/$studentId/records/'
      preLoaderRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/students/$studentId/records/$recordId/include': {
      id: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
      path: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
      fullPath: '/api/meetings/$meetingId/students/$studentId/records/$recordId/include'
      preLoaderRoute: typeof ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppMinutesTemplatesRouteChildren {
  AppMinutesTemplatesIdRoute: typeof AppMinutesTemplatesIdRoute
  AppMinutesTemplatesIndexRoute: typeof AppMinutesTemplatesIndexRoute
}

const AppMinutesTemplatesRouteChildren: AppMinutesTemplatesRouteChildren = {
  AppMinutesTemplatesIdRoute: AppMinutesTemplatesIdRoute,
  AppMinutesTemplatesIndexRoute: AppMinutesTemplatesIndexRoute,
}

const AppMinutesTemplatesRouteWithChildren =
  AppMinutesTemplatesRoute._addFileChildren(AppMinutesTemplatesRouteChildren)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppClassesEnrollRoute: typeof AppClassesEnrollRoute
  AppComponentsIdRoute: typeof AppComponentsIdRoute
  AppMinutesMeetingIdRoute: typeof AppMinutesMeetingIdRoute
  AppMinutesTemplatesRoute: typeof AppMinutesTemplatesRouteWithChildren
  AppRolesIdRoute: typeof AppRolesIdRoute
  AppStaffIdRoute: typeof AppStaffIdRoute
  AppStudentsIdRoute: typeof AppStudentsIdRoute
  AppStudentsImportRoute: typeof AppStudentsImportRoute
  AppClassesIndexRoute: typeof AppClassesIndexRoute
  AppComponentsIndexRoute: typeof AppComponentsIndexRoute
  AppMeetingsIndexRoute: typeof AppMeetingsIndexRoute
  AppMinutesIndexRoute: typeof AppMinutesIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppClassesIdOffersRoute: typeof AppClassesIdOffersRoute
  AppClassesIdStudentsRoute: typeof AppClassesIdStudentsRoute
  AppMeetingsMeetingIdCouncilRoute: typeof AppMeetingsMeetingIdCouncilRoute
  AppMeetingsMeetingIdParticipantsRoute: typeof AppMeetingsMeetingIdParticipantsRoute
  AppMeetingsMeetingIdStudentsRoute: typeof AppMeetingsMeetingIdStudentsRoute
  AppMeetingsMeetingIdIndexRoute: typeof AppMeetingsMeetingIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppClassesEnrollRoute: AppClassesEnrollRoute,
  AppComponentsIdRoute: AppComponentsIdRoute,
  AppMinutesMeetingIdRoute: AppMinutesMeetingIdRoute,
  AppMinutesTemplatesRoute: AppMinutesTemplatesRouteWithChildren,
  AppRolesIdRoute: AppRolesIdRoute,
  AppStaffIdRoute: AppStaffIdRoute,
  AppStudentsIdRoute: AppStudentsIdRoute,
  AppStudentsImportRoute: AppStudentsImportRoute,
  AppClassesIndexRoute: AppClassesIndexRoute,
  AppComponentsIndexRoute: AppComponentsIndexRoute,
  AppMeetingsIndexRoute: AppMeetingsIndexRoute,
  AppMinutesIndexRoute: AppMinutesIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppClassesIdOffersRoute: AppClassesIdOffersRoute,
  AppClassesIdStudentsRoute: AppClassesIdStudentsRoute,
  AppMeetingsMeetingIdCouncilRoute: AppMeetingsMeetingIdCouncilRoute,
  AppMeetingsMeetingIdParticipantsRoute: AppMeetingsMeetingIdParticipantsRoute,
  AppMeetingsMeetingIdStudentsRoute: AppMeetingsMeetingIdStudentsRoute,
  AppMeetingsMeetingIdIndexRoute: AppMeetingsMeetingIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ApiStudentsImportRouteChildren {
  ApiStudentsImportResolveRoute: typeof ApiStudentsImportResolveRoute
}

const ApiStudentsImportRouteChildren: ApiStudentsImportRouteChildren = {
  ApiStudentsImportResolveRoute: ApiStudentsImportResolveRoute,
}

const ApiStudentsImportRouteWithChildren =
  ApiStudentsImportRoute._addFileChildren(ApiStudentsImportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInvitationsStatusRoute: ApiInvitationsStatusRoute,
  ApiInvitationsVerifyRoute: ApiInvitationsVerifyRoute,
  ApiStudentsImportRoute: ApiStudentsImportRouteWithChildren,
  ApiClassesIndexRoute: ApiClassesIndexRoute,
  ApiComponentsIndexRoute: ApiComponentsIndexRoute,
  ApiEnrollmentsIndexRoute: ApiEnrollmentsIndexRoute,
  ApiInvitationsIndexRoute: ApiInvitationsIndexRoute,
  ApiMeetingsIndexRoute: ApiMeetingsIndexRoute,
  ApiMinuteTemplatesIndexRoute: ApiMinuteTemplatesIndexRoute,
  ApiMinutesIndexRoute: ApiMinutesIndexRoute,
  ApiRolesIndexRoute: ApiRolesIndexRoute,
  ApiStaffIndexRoute: ApiStaffIndexRoute,
  ApiStudentsIndexRoute: ApiStudentsIndexRoute,
  ApiClassesIdHistoryRoute: ApiClassesIdHistoryRoute,
  ApiClassesIdOffersRoute: ApiClassesIdOffersRoute,
  ApiClassesIdStudentsRoute: ApiClassesIdStudentsRoute,
  ApiMeetingsMeetingIdParticipantsRoute: ApiMeetingsMeetingIdParticipantsRoute,
  ApiMeetingsMeetingIdReopenRoute: ApiMeetingsMeetingIdReopenRoute,
  ApiStudentsIdHistoryRoute: ApiStudentsIdHistoryRoute,
  ApiStudentsIdRecordsRoute: ApiStudentsIdRecordsRoute,
  ApiAdminUsersIndexRoute: ApiAdminUsersIndexRoute,
  ApiClassesIdIndexRoute: ApiClassesIdIndexRoute,
  ApiComponentsIdIndexRoute: ApiComponentsIdIndexRoute,
  ApiInvitationsIdIndexRoute: ApiInvitationsIdIndexRoute,
  ApiMeetingsMeetingIdIndexRoute: ApiMeetingsMeetingIdIndexRoute,
  ApiMinuteTemplatesIdIndexRoute: ApiMinuteTemplatesIdIndexRoute,
  ApiRolesIdIndexRoute: ApiRolesIdIndexRoute,
  ApiStaffIdIndexRoute: ApiStaffIdIndexRoute,
  ApiStudentsIdIndexRoute: ApiStudentsIdIndexRoute,
  ApiMeetingsMeetingIdGeneralReportsReportIdRoute:
    ApiMeetingsMeetingIdGeneralReportsReportIdRoute,
  ApiMeetingsMeetingIdMinutesApproveRoute:
    ApiMeetingsMeetingIdMinutesApproveRoute,
  ApiMeetingsMeetingIdMinutesContentRoute:
    ApiMeetingsMeetingIdMinutesContentRoute,
  ApiMeetingsMeetingIdRecordsRecordIdRoute:
    ApiMeetingsMeetingIdRecordsRecordIdRoute,
  ApiAdminUsersIdIndexRoute: ApiAdminUsersIdIndexRoute,
  ApiMeetingsMeetingIdClassesIndexRoute: ApiMeetingsMeetingIdClassesIndexRoute,
  ApiMeetingsMeetingIdGeneralReportsIndexRoute:
    ApiMeetingsMeetingIdGeneralReportsIndexRoute,
  ApiMeetingsMeetingIdMinutesIndexRoute: ApiMeetingsMeetingIdMinutesIndexRoute,
  ApiMeetingsMeetingIdClassesClassIdStudentsRoute:
    ApiMeetingsMeetingIdClassesClassIdStudentsRoute,
  ApiMeetingsMeetingIdStudentsStudentIdStatusRoute:
    ApiMeetingsMeetingIdStudentsStudentIdStatusRoute,
  ApiMeetingsMeetingIdClassesClassIdIndexRoute:
    ApiMeetingsMeetingIdClassesClassIdIndexRoute,
  ApiMeetingsMeetingIdMinutesVersionsIndexRoute:
    ApiMeetingsMeetingIdMinutesVersionsIndexRoute,
  ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute:
    ApiMeetingsMeetingIdMinutesVersionsVersionPdfRoute,
  ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute:
    ApiMeetingsMeetingIdStudentsStudentIdRecordsIndexRoute,
  ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute:
    ApiMeetingsMeetingIdStudentsStudentIdRecordsRecordIdIncludeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
